from __future__ import annotations

from collections.abc import Callable


def migration_context_options() -> dict[str, object]:
    """Shared Alembic context options for SQLite-safe migrations."""

    return {
        "render_as_batch": True,
        "compare_type": True,
        "include_object": include_autogenerated_object,
    }


def include_autogenerated_object(
    object_: object,
    _name: str | None,
    type_: str,
    _reflected: bool,
    _compare_to: object | None,
) -> bool:
    """Exclude SQLite virtual tables from autogenerate so revisions hand-write them."""

    if type_ != "table":
        return True

    info = getattr(object_, "info", None)
    if not isinstance(info, dict):
        return True

    return not bool(info.get("sqlite_virtual") or info.get("sqlite_vec"))


IncludeObject = Callable[[object, str | None, str, bool, object | None], bool]


def typed_include_object() -> IncludeObject:
    """Expose a typed include hook for tests and future env customization."""

    return include_autogenerated_object
