from __future__ import annotations

from collections.abc import Callable
from typing import Any

SQLITE_VECTOR_TABLE_NAMES = frozenset({"email_chunks"})


def migration_context_options() -> dict[str, Any]:
    """Shared Alembic context options for SQLite-safe migrations."""

    return {
        "render_as_batch": True,
        "compare_type": True,
        "include_object": include_autogenerated_object,
    }


def include_autogenerated_object(
    object_: object,
    name: str | None,
    type_: str,
    reflected: bool,
    _compare_to: object | None,
) -> bool:
    """Exclude SQLite virtual tables from autogenerate so revisions hand-write them."""

    if type_ != "table":
        return True

    info = getattr(object_, "info", None)
    if isinstance(info, dict) and (info.get("sqlite_virtual") or info.get("sqlite_vec")):
        return False

    table_name = name or getattr(object_, "name", None)
    if reflected and isinstance(table_name, str):
        for vector_table_name in SQLITE_VECTOR_TABLE_NAMES:
            if table_name == vector_table_name or table_name.startswith(
                f"{vector_table_name}_",
            ):
                return False

    return True


IncludeObject = Callable[[object, str | None, str, bool, object | None], bool]


def typed_include_object() -> IncludeObject:
    """Expose a typed include hook for tests and future env customization."""

    return include_autogenerated_object
