from __future__ import annotations

from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

from app.config import AppSettings
from app.db.migrations.config import include_autogenerated_object
from app.db.sqlite_url import sqlite_database_path, sqlite_sync_database_url

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = None


def database_url() -> str:
    """Return a synchronous SQLite URL for Alembic's migration engine."""

    configured_url = config.get_main_option("sqlalchemy.url")
    if configured_url:
        return sqlite_sync_database_url(configured_url)

    return sqlite_sync_database_url(AppSettings().database_url)


def run_migrations_offline() -> None:
    """Run migrations without creating an engine."""

    context.configure(
        url=database_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        render_as_batch=True,
        compare_type=True,
        include_object=include_autogenerated_object,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations with a synchronous SQLAlchemy engine."""

    sqlite_path = sqlite_database_path(database_url())
    sqlite_path.parent.mkdir(parents=True, exist_ok=True)

    configuration = config.get_section(config.config_ini_section, {})
    configuration["sqlalchemy.url"] = database_url()
    connectable = engine_from_config(
        configuration,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            render_as_batch=True,
            compare_type=True,
            include_object=include_autogenerated_object,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
