export default {
  jobTrackerApi: {
    input: "src/api/openapi.json",
    output: {
      target: "src/api/generated.ts",
      client: "fetch",
      mode: "single",
      formatter: "prettier",
      override: {
        header: (info) => [
          "Generated by orval.",
          "Do not edit manually.",
          info.title,
          `OpenAPI spec version: ${info.version}`,
        ],
      },
    },
  },
};
