"""Pydantic DTOs used at application boundaries."""

from .health import HealthResponse
from .provider_config import (
    EmailProviderConfigResponse,
    LLMProviderConfigResponse,
    ProviderConfigRequirementResponse,
    ProviderConfigResponse,
    ProviderConfigUpdateRequest,
    ProviderConfigValues,
    ProviderSecretRequirementResponse,
    ProviderSelection,
)
from .records import (
    ApplicationCorrectionRecord,
    ApplicationEventRecord,
    ApplicationRecord,
    ChatMessageRecord,
    ChatMessageRole,
    EmailBackfillStateRecord,
    EmailBackfillStatus,
    EmailChunkRecord,
    EmailClassificationRecord,
    EmailConnectionRecord,
    EmailSyncStateRecord,
    InsightRecord,
    JobEmailCategory,
    RawEmailBodyRetentionState,
    RawEmailRecord,
)
from .setup import SetupStatusResponse, SetupSubmitRequest, SetupSubmitResponse
from .sync import SyncJobCounts, SyncJobError, SyncJobPhase, SyncJobStatus
from .synthetic_fixture import (
    SyntheticApplication,
    SyntheticApplicationEvent,
    SyntheticApplicationSource,
    SyntheticApplicationStatus,
    SyntheticBodyRetentionState,
    SyntheticEmailClassification,
    SyntheticEventType,
    SyntheticFixtureFile,
    SyntheticFixtureLoadResult,
    SyntheticJobEmailCategory,
    SyntheticRawEmail,
    SyntheticSponsorship,
    SyntheticWorkMode,
)
from .wipe_data import WIPE_DATA_CONFIRMATION, WipeDataRequest, WipeDataResponse

__all__ = [
    "EmailProviderConfigResponse",
    "HealthResponse",
    "LLMProviderConfigResponse",
    "ProviderConfigRequirementResponse",
    "ProviderConfigResponse",
    "ProviderConfigUpdateRequest",
    "ProviderConfigValues",
    "ProviderSecretRequirementResponse",
    "ProviderSelection",
    "ApplicationCorrectionRecord",
    "ApplicationEventRecord",
    "ApplicationRecord",
    "ChatMessageRecord",
    "ChatMessageRole",
    "EmailBackfillStateRecord",
    "EmailBackfillStatus",
    "EmailChunkRecord",
    "EmailClassificationRecord",
    "EmailConnectionRecord",
    "EmailSyncStateRecord",
    "InsightRecord",
    "JobEmailCategory",
    "RawEmailBodyRetentionState",
    "RawEmailRecord",
    "SetupStatusResponse",
    "SetupSubmitRequest",
    "SetupSubmitResponse",
    "SyncJobCounts",
    "SyncJobError",
    "SyncJobPhase",
    "SyncJobStatus",
    "SyntheticApplication",
    "SyntheticApplicationEvent",
    "SyntheticApplicationSource",
    "SyntheticApplicationStatus",
    "SyntheticBodyRetentionState",
    "SyntheticEmailClassification",
    "SyntheticEventType",
    "SyntheticFixtureFile",
    "SyntheticFixtureLoadResult",
    "SyntheticJobEmailCategory",
    "SyntheticRawEmail",
    "SyntheticSponsorship",
    "SyntheticWorkMode",
    "WIPE_DATA_CONFIRMATION",
    "WipeDataRequest",
    "WipeDataResponse",
]
