"""Pydantic DTOs used at application boundaries."""

from .metrics import MetricsFilter
from .processing import (
    ProcessingRunRequest,
    ProcessingRunResult,
    ProcessingRunState,
    ProcessingStatus,
)
from .records import (
    ApplicationCorrectionConflictRecord,
    ApplicationCorrectionRecord,
    ApplicationEventRecord,
    ApplicationRecord,
    ChatMessageRecord,
    ClassificationRunRecord,
    EmailCandidateQueryStrategy,
    EmailChunkRecord,
    EmailChunkSource,
    EmailClassificationCandidate,
    EmailClassificationRecord,
    EmailClassificationResult,
    EmailConnectionRecord,
    EmailFilterDecisionOutcome,
    EmailFilterDecisionRecord,
    EmailTextChunk,
    InsightRecord,
    JobEmailCategory,
    RawEmailBodyRetentionState,
    RawEmailRecord,
)
from .sync import (
    SyncJobCounts,
    SyncJobError,
    SyncJobPhase,
    SyncJobStatus,
)
from .synthetic_fixture import (
    SyntheticApplication,
    SyntheticApplicationEvent,
    SyntheticApplicationSource,
    SyntheticApplicationStatus,
    SyntheticBodyRetentionState,
    SyntheticEmailClassification,
    SyntheticEventType,
    SyntheticFixtureFile,
    SyntheticFixtureLoadResult,
    SyntheticJobEmailCategory,
    SyntheticRawEmail,
    SyntheticSponsorship,
    SyntheticWorkMode,
)

__all__ = [
    "MetricsFilter",
    "ProcessingRunRequest",
    "ProcessingRunResult",
    "ProcessingRunState",
    "ProcessingStatus",
    "ApplicationCorrectionConflictRecord",
    "ApplicationCorrectionRecord",
    "ApplicationEventRecord",
    "ApplicationRecord",
    "ChatMessageRecord",
    "ClassificationRunRecord",
    "EmailCandidateQueryStrategy",
    "EmailChunkRecord",
    "EmailChunkSource",
    "EmailClassificationCandidate",
    "EmailClassificationRecord",
    "EmailClassificationResult",
    "EmailConnectionRecord",
    "EmailFilterDecisionOutcome",
    "EmailFilterDecisionRecord",
    "EmailTextChunk",
    "InsightRecord",
    "JobEmailCategory",
    "RawEmailBodyRetentionState",
    "RawEmailRecord",
    "SyncJobCounts",
    "SyncJobError",
    "SyncJobPhase",
    "SyncJobStatus",
    "SyntheticApplication",
    "SyntheticApplicationEvent",
    "SyntheticApplicationSource",
    "SyntheticApplicationStatus",
    "SyntheticBodyRetentionState",
    "SyntheticEmailClassification",
    "SyntheticEventType",
    "SyntheticFixtureFile",
    "SyntheticFixtureLoadResult",
    "SyntheticJobEmailCategory",
    "SyntheticRawEmail",
    "SyntheticSponsorship",
    "SyntheticWorkMode",
]
