"""Pydantic DTOs used at application boundaries."""

from .application_edit import (
    ApplicationEventEditRequest,
    ApplicationEventEditResponse,
    ApplicationStatusEditRequest,
    ApplicationStatusEditResponse,
)
from .application_merge import ApplicationMergeRequest, ApplicationMergeResponse
from .classification import (
    ClassificationCandidateStats,
    ClassificationPreRunEstimate,
    ClassificationPromptOutput,
    ClassificationReprocessingPlan,
    ClassificationReprocessingStats,
    ClassificationRunResponse,
)
from .correction import (
    ApplicationResetLockRequest,
    ApplicationResetLockResponse,
    ApplicationSplitNewApplication,
    ApplicationSplitRequest,
    ApplicationSplitResponse,
    ApplicationSplitSourceApplication,
)
from .ghost_inference import GhostInferenceRunResponse
from .health import HealthResponse
from .insight import InsightInput, InsightInputEvidence, InsightInputFact
from .provider_config import (
    EmailProviderConfigResponse,
    LLMProviderConfigResponse,
    ProviderConfigRequirementResponse,
    ProviderConfigResponse,
    ProviderConfigUpdateRequest,
    ProviderConfigValues,
    ProviderSecretRequirementResponse,
    ProviderSelection,
)
from .records import (
    ApplicationCorrectionRecord,
    ApplicationEventRecord,
    ApplicationRecord,
    ChatMessageRecord,
    ChatMessageRole,
    ClassificationRunRecord,
    EmailBackfillStateRecord,
    EmailBackfillStatus,
    EmailCandidateQueryStrategy,
    EmailChunkRecord,
    EmailClassificationCandidate,
    EmailClassificationRecord,
    EmailClassificationResult,
    EmailConnectionRecord,
    EmailFilterDecisionOutcome,
    EmailFilterDecisionRecord,
    EmailSyncStateRecord,
    InsightRecord,
    JobEmailCategory,
    RawEmailBodyRetentionState,
    RawEmailRecord,
)
from .setup import SetupStatusResponse, SetupSubmitRequest, SetupSubmitResponse
from .sync import SyncJobCounts, SyncJobError, SyncJobPhase, SyncJobStatus
from .synthetic_fixture import (
    SyntheticApplication,
    SyntheticApplicationEvent,
    SyntheticApplicationSource,
    SyntheticApplicationStatus,
    SyntheticBodyRetentionState,
    SyntheticEmailClassification,
    SyntheticEventType,
    SyntheticFixtureFile,
    SyntheticFixtureLoadResult,
    SyntheticJobEmailCategory,
    SyntheticRawEmail,
    SyntheticSponsorship,
    SyntheticWorkMode,
)
from .wipe_data import WIPE_DATA_CONFIRMATION, WipeDataRequest, WipeDataResponse

__all__ = [
    "ClassificationPromptOutput",
    "EmailProviderConfigResponse",
    "GhostInferenceRunResponse",
    "HealthResponse",
    "LLMProviderConfigResponse",
    "ProviderConfigRequirementResponse",
    "ProviderConfigResponse",
    "ProviderConfigUpdateRequest",
    "ProviderConfigValues",
    "ProviderSecretRequirementResponse",
    "ProviderSelection",
    "ApplicationCorrectionRecord",
    "ApplicationEventEditRequest",
    "ApplicationEventEditResponse",
    "ApplicationEventRecord",
    "ApplicationRecord",
    "ApplicationResetLockRequest",
    "ApplicationResetLockResponse",
    "ApplicationStatusEditRequest",
    "ApplicationStatusEditResponse",
    "ApplicationSplitNewApplication",
    "ApplicationSplitRequest",
    "ApplicationSplitResponse",
    "ApplicationSplitSourceApplication",
    "ChatMessageRecord",
    "ChatMessageRole",
    "ClassificationRunRecord",
    "ClassificationCandidateStats",
    "ClassificationPreRunEstimate",
    "ClassificationReprocessingPlan",
    "ClassificationReprocessingStats",
    "ClassificationRunResponse",
    "ApplicationMergeRequest",
    "ApplicationMergeResponse",
    "EmailBackfillStateRecord",
    "EmailBackfillStatus",
    "EmailCandidateQueryStrategy",
    "EmailChunkRecord",
    "EmailClassificationCandidate",
    "EmailClassificationRecord",
    "EmailClassificationResult",
    "EmailConnectionRecord",
    "EmailFilterDecisionOutcome",
    "EmailFilterDecisionRecord",
    "EmailSyncStateRecord",
    "InsightRecord",
    "InsightInput",
    "InsightInputEvidence",
    "InsightInputFact",
    "JobEmailCategory",
    "RawEmailBodyRetentionState",
    "RawEmailRecord",
    "SetupStatusResponse",
    "SetupSubmitRequest",
    "SetupSubmitResponse",
    "SyncJobCounts",
    "SyncJobError",
    "SyncJobPhase",
    "SyncJobStatus",
    "SyntheticApplication",
    "SyntheticApplicationEvent",
    "SyntheticApplicationSource",
    "SyntheticApplicationStatus",
    "SyntheticBodyRetentionState",
    "SyntheticEmailClassification",
    "SyntheticEventType",
    "SyntheticFixtureFile",
    "SyntheticFixtureLoadResult",
    "SyntheticJobEmailCategory",
    "SyntheticRawEmail",
    "SyntheticSponsorship",
    "SyntheticWorkMode",
    "WIPE_DATA_CONFIRMATION",
    "WipeDataRequest",
    "WipeDataResponse",
]
