"""Email provider Strategy interface."""

from .gmail import GmailEmailProvider
from .provider import (
    EmailAccountRef,
    EmailAddress,
    EmailAttachmentPolicy,
    EmailAuthorizationCallbackRequest,
    EmailAuthorizationStartRequest,
    EmailAuthorizationStartResult,
    EmailBodyBatch,
    EmailBodyFetchFailure,
    EmailBodyFetchFailureReason,
    EmailBodyFetchRequest,
    EmailBodySource,
    EmailConnection,
    EmailMessageBody,
    EmailMessageMetadata,
    EmailMessageRef,
    EmailMetadataListRequest,
    EmailMetadataPage,
    EmailProvider,
    EmailProviderAuthError,
    EmailProviderCapabilities,
    EmailProviderCursor,
    EmailProviderError,
    EmailProviderTransientError,
    EmailSyncCursorExpiredError,
    EmailSyncMode,
)

__all__ = [
    "EmailAccountRef",
    "EmailAddress",
    "EmailAttachmentPolicy",
    "EmailAuthorizationCallbackRequest",
    "EmailAuthorizationStartRequest",
    "EmailAuthorizationStartResult",
    "EmailBodyBatch",
    "EmailBodyFetchFailure",
    "EmailBodyFetchFailureReason",
    "EmailBodyFetchRequest",
    "EmailBodySource",
    "EmailConnection",
    "EmailMessageBody",
    "EmailMessageMetadata",
    "EmailMessageRef",
    "EmailMetadataListRequest",
    "EmailMetadataPage",
    "EmailProvider",
    "EmailProviderAuthError",
    "EmailProviderCapabilities",
    "EmailProviderCursor",
    "EmailProviderError",
    "EmailProviderTransientError",
    "EmailSyncCursorExpiredError",
    "EmailSyncMode",
    "GmailEmailProvider",
]
