from __future__ import annotations

import sqlite3
from importlib import import_module
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from app.db.migrations.config import (
    include_autogenerated_object,
    migration_context_options,
)
from app.db.sqlite_url import sqlite_sync_database_url
from pytest import MonkeyPatch
from sqlalchemy import Column, Integer, MetaData, Table

BACKEND_ROOT = Path(__file__).resolve().parents[1]


def alembic_config(database_url: str | None = None) -> Config:
    config = Config(str(BACKEND_ROOT / "alembic.ini"))
    if database_url is not None:
        config.set_main_option("sqlalchemy.url", database_url)
    return config


def test_alembic_config_points_to_app_migrations_directory() -> None:
    config = alembic_config()
    script = ScriptDirectory.from_config(config)
    script_location = config.get_main_option("script_location")

    assert script_location is not None
    assert Path(script_location) == BACKEND_ROOT / "app" / "db" / "migrations"
    assert Path(script.dir) == BACKEND_ROOT / "app" / "db" / "migrations"
    assert Path(script.versions) == BACKEND_ROOT / "app" / "db" / "migrations" / "versions"


def test_alembic_context_options_enable_sqlite_batch_mode() -> None:
    options = migration_context_options()

    assert options["render_as_batch"] is True
    assert options["compare_type"] is True
    assert options["include_object"] is include_autogenerated_object


def test_sqlite_sync_database_url_preserves_sqlite_slash_forms(tmp_path: Path) -> None:
    database_path = tmp_path / "jobtracker.sqlite3"

    assert sqlite_sync_database_url("sqlite+aiosqlite:///./.jobtracker/jobtracker.sqlite3") == (
        "sqlite:///./.jobtracker/jobtracker.sqlite3"
    )
    assert sqlite_sync_database_url(f"sqlite+aiosqlite:///{database_path}") == (
        f"sqlite:///{database_path}"
    )
    assert sqlite_sync_database_url("sqlite:///./.jobtracker/jobtracker.sqlite3") == (
        "sqlite:///./.jobtracker/jobtracker.sqlite3"
    )


def test_core_schema_revision_does_not_include_later_recurring_feedback_type() -> None:
    migration = import_module("app.db.migrations.versions.20260705_0002_core_schema")

    assert "recurring_feedback" not in migration.INSIGHT_TYPES


def test_virtual_tables_are_excluded_from_autogenerate() -> None:
    metadata = MetaData()
    regular_table = Table("raw_emails", metadata, Column("id", Integer, primary_key=True))
    virtual_table = Table(
        "email_chunks",
        metadata,
        Column("rowid", Integer, primary_key=True),
        info={"sqlite_virtual": True},
    )

    assert include_autogenerated_object(regular_table, "raw_emails", "table", False, None)
    assert not include_autogenerated_object(virtual_table, "email_chunks", "table", False, None)


def test_reflected_vector_tables_are_excluded_from_autogenerate() -> None:
    metadata = MetaData()
    reflected_vector_table = Table("email_chunks", metadata)
    reflected_shadow_table = Table("email_chunks_chunks", metadata)

    assert not include_autogenerated_object(
        reflected_vector_table,
        "email_chunks",
        "table",
        True,
        None,
    )
    assert not include_autogenerated_object(
        reflected_shadow_table,
        "email_chunks_chunks",
        "table",
        True,
        None,
    )


def test_alembic_uses_settings_database_url_by_default(
    tmp_path: Path,
    monkeypatch: MonkeyPatch,
) -> None:
    database_path = tmp_path / "from-settings.sqlite3"
    monkeypatch.setenv("JOBTRACKER_DATABASE_URL", f"sqlite+aiosqlite:///{database_path}")
    config = alembic_config()

    command.ensure_version(config)

    with sqlite3.connect(database_path) as connection:
        table_names = {
            row[0]
            for row in connection.execute(
                "SELECT name FROM sqlite_master WHERE type = 'table'",
            )
        }

    assert "alembic_version" in table_names


def test_alembic_can_create_version_table_against_sqlite(tmp_path: Path) -> None:
    database_path = tmp_path / "jobtracker.sqlite3"
    config = alembic_config(f"sqlite+aiosqlite:///{database_path}")

    command.ensure_version(config)

    with sqlite3.connect(database_path) as connection:
        table_names = {
            row[0]
            for row in connection.execute(
                "SELECT name FROM sqlite_master WHERE type = 'table'",
            )
        }

    assert "alembic_version" in table_names


def test_alembic_upgrade_creates_jt020_core_schema(tmp_path: Path) -> None:
    database_path = tmp_path / "jobtracker.sqlite3"
    config = alembic_config(f"sqlite+aiosqlite:///{database_path}")

    command.upgrade(config, "head")

    with sqlite3.connect(database_path) as connection:
        load_sqlite_vec(connection)
        table_names = sqlite_table_names(connection)

        assert {
            "email_connections",
            "raw_emails",
            "email_filter_decisions",
            "email_classifications",
            "applications",
            "application_events",
            "application_corrections",
            "application_correction_conflicts",
            "insights",
            "chat_messages",
            "classification_runs",
            "email_chunks",
        }.issubset(table_names)
        assert sqlite_column_names(connection, "raw_emails") == [
            "id",
            "thread_id",
            "from_addr",
            "to_addr",
            "subject",
            "sent_at",
            "body_text",
            "body_retention_state",
            "labels",
            "provider",
            "ingested_at",
            "public_id",
        ]
        assert sqlite_column_names(connection, "email_connections") == [
            "provider",
            "account_id",
            "display_email",
            "credential_ref_kind",
            "credential_ref_provider",
            "credential_ref_name",
            "granted_scopes",
            "connected_at",
            "credential_expires_at",
            "reauth_required",
            "updated_at",
        ]
        assert sqlite_column_names(connection, "email_classifications") == [
            "email_id",
            "is_job_related",
            "category",
            "confidence",
            "model",
            "prompt_version",
            "classified_at",
        ]
        assert sqlite_column_names(connection, "classification_runs") == [
            "id",
            "provider",
            "model",
            "prompt_version",
            "started_at",
            "completed_at",
            "candidate_count",
            "classified_count",
            "prompt_tokens",
            "completion_tokens",
            "total_tokens",
            "estimated_cost_usd",
        ]
        assert sqlite_column_names(connection, "email_filter_decisions") == [
            "email_id",
            "strategy",
            "outcome",
            "reason",
            "decided_at",
        ]
        assert sqlite_column_names(connection, "applications") == [
            "id",
            "company",
            "role_title",
            "source",
            "first_seen_at",
            "current_status",
            "salary_min",
            "salary_max",
            "currency",
            "location",
            "work_mode",
            "seniority",
            "sponsorship",
            "tech_stack",
            "last_activity_at",
            "manual_lock",
            "created_at",
            "updated_at",
        ]
        assert sqlite_column_names(connection, "application_events") == [
            "id",
            "application_id",
            "email_id",
            "event_type",
            "event_at",
            "extract_note",
            "extracted_status",
        ]
        assert sqlite_column_names(connection, "application_corrections") == [
            "id",
            "application_id",
            "correction_type",
            "before_json",
            "after_json",
            "reason",
            "created_at",
        ]
        assert sqlite_column_names(connection, "application_correction_conflicts") == [
            "id",
            "application_id",
            "conflict_key",
            "conflict_type",
            "existing_json",
            "proposed_json",
            "evidence_email_id",
            "created_at",
        ]
        assert sqlite_column_names(connection, "chat_messages") == [
            "id",
            "conversation_id",
            "role",
            "content",
            "citations_json",
            "tool_outputs_json",
            "created_at",
            "turn_id",
            "route",
            "answer_kind",
            "follow_up_prompts_json",
        ]
        assert sqlite_column_names(connection, "insights") == [
            "id",
            "type",
            "content",
            "inputs_hash",
            "is_stale",
            "model",
            "generated_at",
            "citations_json",
        ]
        assert sqlite_column_names(connection, "email_chunks") == [
            "rowid",
            "email_id",
            "chunk_index",
            "content",
            "embedding",
        ]
        email_chunks_sql = connection.execute(
            "SELECT sql FROM sqlite_schema WHERE name = 'email_chunks'",
        ).fetchone()
        assert email_chunks_sql is not None
        assert "+content TEXT" in email_chunks_sql[0]
        assert foreign_key_targets(connection, "email_classifications") == {
            ("email_id", "raw_emails", "id"),
        }
        assert foreign_key_targets(connection, "email_filter_decisions") == {
            ("email_id", "raw_emails", "id"),
        }
        assert foreign_key_targets(connection, "application_events") == {
            ("application_id", "applications", "id"),
            ("email_id", "raw_emails", "id"),
        }
        assert foreign_key_targets(connection, "application_corrections") == {
            ("application_id", "applications", "id"),
        }
        assert foreign_key_targets(connection, "application_correction_conflicts") == {
            ("application_id", "applications", "id"),
            ("evidence_email_id", "raw_emails", "id"),
        }
        assert foreign_key_targets(connection, "chat_messages") == set()


def test_application_corrections_store_audited_manual_overrides(
    tmp_path: Path,
) -> None:
    database_path = tmp_path / "jobtracker.sqlite3"
    config = alembic_config(f"sqlite+aiosqlite:///{database_path}")

    command.upgrade(config, "head")

    with sqlite3.connect(database_path) as connection:
        connection.execute("PRAGMA foreign_keys=ON")
        insert_application(connection)

        connection.execute(
            """
            INSERT INTO application_corrections (
                application_id,
                correction_type,
                before_json,
                after_json,
                reason,
                created_at
            ) VALUES (?, ?, ?, ?, ?, ?)
            """,
            (
                "app_1",
                "status_edit",
                '{"current_status": "applied"}',
                '{"current_status": "rejected"}',
                "User corrected aggregation status.",
                "2026-07-31T00:00:00Z",
            ),
        )

        row = connection.execute(
            """
            SELECT
                application_id,
                correction_type,
                before_json,
                after_json,
                reason,
                created_at
            FROM application_corrections
            """,
        ).fetchone()

    assert row == (
        "app_1",
        "status_edit",
        '{"current_status": "applied"}',
        '{"current_status": "rejected"}',
        "User corrected aggregation status.",
        "2026-07-31T00:00:00Z",
    )


def test_application_corrections_reject_unknown_correction_type(
    tmp_path: Path,
) -> None:
    database_path = tmp_path / "jobtracker.sqlite3"
    config = alembic_config(f"sqlite+aiosqlite:///{database_path}")

    command.upgrade(config, "head")

    with sqlite3.connect(database_path) as connection:
        connection.execute("PRAGMA foreign_keys=ON")
        insert_application(connection)

        with pytest.raises(sqlite3.IntegrityError):
            connection.execute(
                """
                INSERT INTO application_corrections (
                    application_id,
                    correction_type,
                    before_json,
                    after_json,
                    created_at
                ) VALUES (?, ?, ?, ?, ?)
                """,
                (
                    "app_1",
                    "invalid_edit",
                    '{"current_status": "applied"}',
                    '{"current_status": "rejected"}',
                    "2026-07-31T00:00:00Z",
                ),
            )


@pytest.mark.parametrize(
    ("before_json", "after_json"),
    [
        ("not json", '{"current_status": "rejected"}'),
        ('{"current_status": "applied"}', "not json"),
    ],
)
def test_application_corrections_reject_malformed_json_snapshots(
    tmp_path: Path,
    before_json: str,
    after_json: str,
) -> None:
    database_path = tmp_path / "jobtracker.sqlite3"
    config = alembic_config(f"sqlite+aiosqlite:///{database_path}")

    command.upgrade(config, "head")

    with sqlite3.connect(database_path) as connection:
        connection.execute("PRAGMA foreign_keys=ON")
        insert_application(connection)

        with pytest.raises(sqlite3.IntegrityError):
            connection.execute(
                """
                INSERT INTO application_corrections (
                    application_id,
                    correction_type,
                    before_json,
                    after_json,
                    created_at
                ) VALUES (?, ?, ?, ?, ?)
                """,
                (
                    "app_1",
                    "status_edit",
                    before_json,
                    after_json,
                    "2026-07-31T00:00:00Z",
                ),
            )


def test_application_corrections_cascade_with_application_deletes(
    tmp_path: Path,
) -> None:
    database_path = tmp_path / "jobtracker.sqlite3"
    config = alembic_config(f"sqlite+aiosqlite:///{database_path}")

    command.upgrade(config, "head")

    with sqlite3.connect(database_path) as connection:
        connection.execute("PRAGMA foreign_keys=ON")
        insert_application(connection)
        connection.execute(
            """
            INSERT INTO application_corrections (
                application_id,
                correction_type,
                before_json,
                after_json,
                created_at
            ) VALUES (?, ?, ?, ?, ?)
            """,
            (
                "app_1",
                "reset_lock",
                '{"manual_lock": true}',
                '{"manual_lock": false}',
                "2026-07-31T00:00:00Z",
            ),
        )

        connection.execute("DELETE FROM applications WHERE id = ?", ("app_1",))

        assert connection.execute(
            "SELECT COUNT(*) FROM application_corrections",
        ).fetchone() == (0,)


def test_application_correction_conflicts_store_conflicting_evidence(
    tmp_path: Path,
) -> None:
    database_path = tmp_path / "jobtracker.sqlite3"
    config = alembic_config(f"sqlite+aiosqlite:///{database_path}")

    command.upgrade(config, "head")

    with sqlite3.connect(database_path) as connection:
        connection.execute("PRAGMA foreign_keys=ON")
        insert_application(connection)
        insert_raw_email(connection, email_id="email_1")

        connection.execute(
            """
            INSERT INTO application_correction_conflicts (
                application_id,
                conflict_key,
                conflict_type,
                existing_json,
                proposed_json,
                evidence_email_id,
                created_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            (
                "app_1",
                "application_summary:app_1:email_1",
                "application_summary",
                '{"application":{"current_status":"rejected"}}',
                '{"application":{"current_status":"offer"}}',
                "email_1",
                "2026-07-31T00:00:00Z",
            ),
        )

        row = connection.execute(
            """
            SELECT
                application_id,
                conflict_key,
                conflict_type,
                existing_json,
                proposed_json,
                evidence_email_id,
                created_at
            FROM application_correction_conflicts
            """,
        ).fetchone()

    assert row == (
        "app_1",
        "application_summary:app_1:email_1",
        "application_summary",
        '{"application":{"current_status":"rejected"}}',
        '{"application":{"current_status":"offer"}}',
        "email_1",
        "2026-07-31T00:00:00Z",
    )


def test_application_correction_conflicts_are_idempotent_by_key(
    tmp_path: Path,
) -> None:
    database_path = tmp_path / "jobtracker.sqlite3"
    config = alembic_config(f"sqlite+aiosqlite:///{database_path}")

    command.upgrade(config, "head")

    with sqlite3.connect(database_path) as connection:
        connection.execute("PRAGMA foreign_keys=ON")
        insert_application(connection)
        insert_raw_email(connection, email_id="email_1")

        for proposed_status in ("offer", "interview"):
            connection.execute(
                """
                INSERT INTO application_correction_conflicts (
                    application_id,
                    conflict_key,
                    conflict_type,
                    existing_json,
                    proposed_json,
                    evidence_email_id,
                    created_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?)
                ON CONFLICT(conflict_key) DO UPDATE SET
                    existing_json = excluded.existing_json,
                    proposed_json = excluded.proposed_json,
                    evidence_email_id = excluded.evidence_email_id
                """,
                (
                    "app_1",
                    "application_summary:app_1:email_1",
                    "application_summary",
                    '{"application":{"current_status":"rejected"}}',
                    f'{{"application":{{"current_status":"{proposed_status}"}}}}',
                    "email_1",
                    "2026-07-31T00:00:00Z",
                ),
            )

        row = connection.execute(
            """
            SELECT COUNT(*), proposed_json
            FROM application_correction_conflicts
            """,
        ).fetchone()

    assert row == (1, '{"application":{"current_status":"interview"}}')


def test_chat_messages_store_compact_history_rows(tmp_path: Path) -> None:
    database_path = tmp_path / "jobtracker.sqlite3"
    config = alembic_config(f"sqlite+aiosqlite:///{database_path}")

    command.upgrade(config, "head")

    with sqlite3.connect(database_path) as connection:
        insert_chat_message(
            connection,
            citations_json='[{"application_id": "app_1", "email_id": "email_1"}]',
            tool_outputs_json='[{"tool": "structured_query", "result_id": "metric_1"}]',
        )

        row = connection.execute(
            """
            SELECT
                conversation_id,
                role,
                content,
                citations_json,
                tool_outputs_json,
                created_at
            FROM chat_messages
            WHERE conversation_id = ?
            """,
            ("conversation-1",),
        ).fetchone()

    assert row == (
        "conversation-1",
        "assistant",
        "You have one overdue follow-up.",
        '[{"application_id": "app_1", "email_id": "email_1"}]',
        '[{"tool": "structured_query", "result_id": "metric_1"}]',
        "2026-07-31T00:00:00Z",
    )


def test_classification_runs_store_tokens_and_estimated_cost(tmp_path: Path) -> None:
    database_path = tmp_path / "jobtracker.sqlite3"
    config = alembic_config(f"sqlite+aiosqlite:///{database_path}")

    command.upgrade(config, "head")

    with sqlite3.connect(database_path) as connection:
        insert_classification_run(connection)

        row = connection.execute(
            """
            SELECT
                provider,
                model,
                prompt_version,
                candidate_count,
                classified_count,
                prompt_tokens,
                completion_tokens,
                total_tokens,
                estimated_cost_usd
            FROM classification_runs
            WHERE id = ?
            """,
            ("classification-run-1",),
        ).fetchone()

    assert row is not None
    assert row[:-1] == (
        "azure_openai",
        "gpt-4.1-mini",
        "prompt-v1",
        3,
        3,
        120,
        30,
        150,
    )
    assert float(row[-1]) == pytest.approx(0.00045)


@pytest.mark.parametrize(
    ("override", "value"),
    [
        ("candidate_count", -1),
        ("classified_count", 4),
        ("total_tokens", 149),
        ("estimated_cost_usd", -0.000001),
    ],
)
def test_classification_runs_reject_invalid_accounting_values(
    tmp_path: Path,
    override: str,
    value: object,
) -> None:
    database_path = tmp_path / "jobtracker.sqlite3"
    config = alembic_config(f"sqlite+aiosqlite:///{database_path}")

    command.upgrade(config, "head")

    with (
        sqlite3.connect(database_path) as connection,
        pytest.raises(sqlite3.IntegrityError),
    ):
        insert_classification_run(connection, **{override: value})


def test_chat_messages_reject_unknown_role(tmp_path: Path) -> None:
    database_path = tmp_path / "jobtracker.sqlite3"
    config = alembic_config(f"sqlite+aiosqlite:///{database_path}")

    command.upgrade(config, "head")

    with (
        sqlite3.connect(database_path) as connection,
        pytest.raises(sqlite3.IntegrityError),
    ):
        insert_chat_message(connection, role="sql_writer")


@pytest.mark.parametrize(
    ("citations_json", "tool_outputs_json"),
    [
        ("not json", "[]"),
        ("{}", "[]"),
        ("[]", "not json"),
        ("[]", "{}"),
    ],
)
def test_chat_messages_reject_non_array_json_payloads(
    tmp_path: Path,
    citations_json: str,
    tool_outputs_json: str,
) -> None:
    database_path = tmp_path / "jobtracker.sqlite3"
    config = alembic_config(f"sqlite+aiosqlite:///{database_path}")

    command.upgrade(config, "head")

    with (
        sqlite3.connect(database_path) as connection,
        pytest.raises(sqlite3.IntegrityError),
    ):
        insert_chat_message(
            connection,
            citations_json=citations_json,
            tool_outputs_json=tool_outputs_json,
        )


def test_application_events_allow_ghost_inferred_without_email(tmp_path: Path) -> None:
    database_path = tmp_path / "jobtracker.sqlite3"
    config = alembic_config(f"sqlite+aiosqlite:///{database_path}")

    command.upgrade(config, "head")

    with sqlite3.connect(database_path) as connection:
        connection.execute("PRAGMA foreign_keys=ON")
        connection.execute(
            """
            INSERT INTO applications (
                id,
                company,
                role_title,
                source,
                first_seen_at,
                current_status,
                last_activity_at,
                created_at,
                updated_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                "app_1",
                "Example Co",
                "Software Engineer",
                "company_site",
                "2026-07-01T00:00:00Z",
                "ghosted",
                "2026-07-31T00:00:00Z",
                "2026-07-01T00:00:00Z",
                "2026-07-31T00:00:00Z",
            ),
        )

        connection.execute(
            """
            INSERT INTO application_events (
                id,
                application_id,
                email_id,
                event_type,
                event_at
            ) VALUES (?, ?, ?, ?, ?)
            """,
            (
                "event_1",
                "app_1",
                None,
                "ghost_inferred",
                "2026-07-31T00:00:00Z",
            ),
        )

        assert connection.execute(
            "SELECT email_id FROM application_events WHERE id = 'event_1'",
        ).fetchone() == (None,)


def test_application_events_reject_ghost_inferred_with_email(tmp_path: Path) -> None:
    database_path = tmp_path / "jobtracker.sqlite3"
    config = alembic_config(f"sqlite+aiosqlite:///{database_path}")

    command.upgrade(config, "head")

    with sqlite3.connect(database_path) as connection:
        connection.execute("PRAGMA foreign_keys=ON")
        connection.execute(
            """
            INSERT INTO raw_emails (
                id,
                body_retention_state,
                labels,
                provider,
                ingested_at
            ) VALUES (?, ?, ?, ?, ?)
            """,
            (
                "email_1",
                "metadata_only",
                "[]",
                "gmail",
                "2026-07-01T00:00:00Z",
            ),
        )
        connection.execute(
            """
            INSERT INTO applications (
                id,
                company,
                role_title,
                source,
                first_seen_at,
                current_status,
                last_activity_at,
                created_at,
                updated_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                "app_1",
                "Example Co",
                "Software Engineer",
                "company_site",
                "2026-07-01T00:00:00Z",
                "ghosted",
                "2026-07-31T00:00:00Z",
                "2026-07-01T00:00:00Z",
                "2026-07-31T00:00:00Z",
            ),
        )

        with pytest.raises(sqlite3.IntegrityError):
            connection.execute(
                """
                INSERT INTO application_events (
                    id,
                    application_id,
                    email_id,
                    event_type,
                    event_at
                ) VALUES (?, ?, ?, ?, ?)
                """,
                (
                    "event_1",
                    "app_1",
                    "email_1",
                    "ghost_inferred",
                    "2026-07-31T00:00:00Z",
                ),
            )


def test_application_events_require_email_for_evidence_backed_events(
    tmp_path: Path,
) -> None:
    database_path = tmp_path / "jobtracker.sqlite3"
    config = alembic_config(f"sqlite+aiosqlite:///{database_path}")

    command.upgrade(config, "head")

    with sqlite3.connect(database_path) as connection:
        connection.execute("PRAGMA foreign_keys=ON")
        connection.execute(
            """
            INSERT INTO applications (
                id,
                company,
                role_title,
                source,
                first_seen_at,
                current_status,
                last_activity_at,
                created_at,
                updated_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                "app_1",
                "Example Co",
                "Software Engineer",
                "company_site",
                "2026-07-01T00:00:00Z",
                "rejected",
                "2026-07-31T00:00:00Z",
                "2026-07-01T00:00:00Z",
                "2026-07-31T00:00:00Z",
            ),
        )

        with pytest.raises(sqlite3.IntegrityError):
            connection.execute(
                """
                INSERT INTO application_events (
                    id,
                    application_id,
                    email_id,
                    event_type,
                    event_at
                ) VALUES (?, ?, ?, ?, ?)
                """,
                (
                    "event_1",
                    "app_1",
                    None,
                    "rejection",
                    "2026-07-31T00:00:00Z",
                ),
            )


def test_application_source_changes_mark_cached_insights_stale(tmp_path: Path) -> None:
    database_path = tmp_path / "jobtracker.sqlite3"
    config = alembic_config(f"sqlite+aiosqlite:///{database_path}")

    command.upgrade(config, "head")

    with sqlite3.connect(database_path) as connection:
        insert_cached_insight(connection)

        insert_application(connection)

        assert cached_insight_is_stale(connection)

        set_cached_insight_stale(connection, False)
        connection.execute(
            "UPDATE applications SET current_status = ? WHERE id = ?",
            ("rejected", "app_1"),
        )

        assert cached_insight_is_stale(connection)

        set_cached_insight_stale(connection, False)
        connection.execute("DELETE FROM applications WHERE id = ?", ("app_1",))

        assert cached_insight_is_stale(connection)


def test_application_event_source_changes_mark_cached_insights_stale(
    tmp_path: Path,
) -> None:
    database_path = tmp_path / "jobtracker.sqlite3"
    config = alembic_config(f"sqlite+aiosqlite:///{database_path}")

    command.upgrade(config, "head")

    with sqlite3.connect(database_path) as connection:
        insert_application(connection)
        insert_cached_insight(connection)

        insert_application_event(connection)

        assert cached_insight_is_stale(connection)

        set_cached_insight_stale(connection, False)
        connection.execute(
            "UPDATE application_events SET extract_note = ? WHERE id = ?",
            ("Ghosted after thirty days of silence.", "event_1"),
        )

        assert cached_insight_is_stale(connection)

        set_cached_insight_stale(connection, False)
        connection.execute("DELETE FROM application_events WHERE id = ?", ("event_1",))

        assert cached_insight_is_stale(connection)


def test_cited_raw_email_source_changes_mark_cached_insights_stale(
    tmp_path: Path,
) -> None:
    database_path = tmp_path / "jobtracker.sqlite3"
    config = alembic_config(f"sqlite+aiosqlite:///{database_path}")

    command.upgrade(config, "head")

    with sqlite3.connect(database_path) as connection:
        connection.execute("PRAGMA foreign_keys=ON")
        insert_application(connection)
        insert_raw_email(connection)
        insert_evidence_backed_application_event(connection)
        insert_cached_insight(connection)

        connection.execute(
            "UPDATE raw_emails SET body_text = ? WHERE id = ?",
            ("Updated retained feedback.", "email_1"),
        )

        assert cached_insight_is_stale(connection)

        set_cached_insight_stale(connection, False)
        connection.execute(
            "UPDATE raw_emails SET labels = ? WHERE id = ?",
            ('["INBOX", "STARRED"]', "email_1"),
        )

        assert not cached_insight_is_stale(connection)


def test_application_timestamp_only_update_keeps_cached_insights_fresh(
    tmp_path: Path,
) -> None:
    database_path = tmp_path / "jobtracker.sqlite3"
    config = alembic_config(f"sqlite+aiosqlite:///{database_path}")

    command.upgrade(config, "head")

    with sqlite3.connect(database_path) as connection:
        insert_application(connection)
        insert_cached_insight(connection)

        connection.execute(
            "UPDATE applications SET updated_at = ? WHERE id = ?",
            ("2026-07-02T00:00:00Z", "app_1"),
        )

        assert not cached_insight_is_stale(connection)


def test_alembic_downgrade_removes_jt020_core_schema(tmp_path: Path) -> None:
    database_path = tmp_path / "jobtracker.sqlite3"
    config = alembic_config(f"sqlite+aiosqlite:///{database_path}")

    command.upgrade(config, "head")
    command.downgrade(config, "20260705_0001")

    with sqlite3.connect(database_path) as connection:
        table_names = sqlite_table_names(connection)

        assert "email_sync_state" in table_names
        assert "raw_emails" not in table_names
        assert "email_classifications" not in table_names
        assert "applications" not in table_names
        assert "application_events" not in table_names
        assert "application_corrections" not in table_names
        assert "chat_messages" not in table_names
        assert "classification_runs" not in table_names
        assert "insights" not in table_names
        assert not any(table_name.startswith("email_chunks") for table_name in table_names)


def test_alembic_downgrade_removes_chat_history_schema(tmp_path: Path) -> None:
    database_path = tmp_path / "jobtracker.sqlite3"
    config = alembic_config(f"sqlite+aiosqlite:///{database_path}")

    command.upgrade(config, "head")
    command.downgrade(config, "20260705_0005")

    with sqlite3.connect(database_path) as connection:
        table_names = sqlite_table_names(connection)

        assert "application_corrections" in table_names
        assert "chat_messages" not in table_names
        assert "classification_runs" not in table_names


def test_alembic_env_uses_shared_sqlite_vec_loader() -> None:
    env_py = BACKEND_ROOT / "app" / "db" / "migrations" / "env.py"

    env_source = env_py.read_text()

    assert "load_sqlite_vec_sync" in env_source
    assert "settings.sqlite_vec_extension_path" in env_source


def sqlite_table_names(connection: sqlite3.Connection) -> set[str]:
    return {
        str(row[0])
        for row in connection.execute(
            "SELECT name FROM sqlite_master WHERE type = 'table'",
        )
    }


def sqlite_column_names(connection: sqlite3.Connection, table_name: str) -> list[str]:
    return [str(row[1]) for row in connection.execute(f"PRAGMA table_info({table_name})")]


def foreign_key_targets(
    connection: sqlite3.Connection,
    table_name: str,
) -> set[tuple[str, str, str]]:
    return {
        (str(row[3]), str(row[2]), str(row[4]))
        for row in connection.execute(f"PRAGMA foreign_key_list({table_name})")
    }


def insert_application(connection: sqlite3.Connection) -> None:
    connection.execute(
        """
        INSERT INTO applications (
            id,
            company,
            role_title,
            source,
            first_seen_at,
            current_status,
            last_activity_at,
            created_at,
            updated_at
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            "app_1",
            "Example Co",
            "Software Engineer",
            "company_site",
            "2026-07-01T00:00:00Z",
            "applied",
            "2026-07-01T00:00:00Z",
            "2026-07-01T00:00:00Z",
            "2026-07-01T00:00:00Z",
        ),
    )


def insert_raw_email(
    connection: sqlite3.Connection,
    *,
    email_id: str = "email_1",
) -> None:
    connection.execute(
        """
        INSERT INTO raw_emails (
            id,
            thread_id,
            from_addr,
            to_addr,
            subject,
            sent_at,
            body_text,
            body_retention_state,
            labels,
            provider,
            ingested_at
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            email_id,
            "thread_1",
            "jobs@example.test",
            "applicant@example.test",
            "Application update",
            "2026-07-31T00:00:00Z",
            "Synthetic retained body.",
            "retained",
            "[]",
            "gmail",
            "2026-07-31T00:00:00Z",
        ),
    )


def insert_application_event(connection: sqlite3.Connection) -> None:
    connection.execute(
        """
        INSERT INTO application_events (
            id,
            application_id,
            email_id,
            event_type,
            event_at,
            extract_note
        ) VALUES (?, ?, ?, ?, ?, ?)
        """,
        (
            "event_1",
            "app_1",
            None,
            "ghost_inferred",
            "2026-08-01T00:00:00Z",
            "Ghosted after thirty days.",
        ),
    )


def insert_evidence_backed_application_event(connection: sqlite3.Connection) -> None:
    connection.execute(
        """
        INSERT INTO application_events (
            id,
            application_id,
            email_id,
            event_type,
            event_at,
            extract_note
        ) VALUES (?, ?, ?, ?, ?, ?)
        """,
        (
            "event_1",
            "app_1",
            "email_1",
            "feedback",
            "2026-07-05T00:00:00Z",
            "Feedback mentioned platform depth.",
        ),
    )


def insert_cached_insight(connection: sqlite3.Connection) -> None:
    connection.execute(
        """
        INSERT INTO insights (
            type,
            content,
            inputs_hash,
            is_stale,
            model,
            generated_at
        ) VALUES (?, ?, ?, ?, ?, ?)
        """,
        (
            "story",
            "Your recent search is weighted toward platform roles.",
            "inputs-hash-v1",
            0,
            "gpt-4.1-mini",
            "2026-07-01T12:00:00+00:00",
        ),
    )


def cached_insight_is_stale(connection: sqlite3.Connection) -> bool:
    row = connection.execute(
        "SELECT is_stale FROM insights WHERE type = ?",
        ("story",),
    ).fetchone()
    assert row is not None
    return bool(row[0])


def set_cached_insight_stale(connection: sqlite3.Connection, is_stale: bool) -> None:
    connection.execute(
        "UPDATE insights SET is_stale = ? WHERE type = ?",
        (int(is_stale), "story"),
    )


def insert_chat_message(
    connection: sqlite3.Connection,
    *,
    role: str = "assistant",
    citations_json: str = "[]",
    tool_outputs_json: str = "[]",
) -> None:
    connection.execute(
        """
        INSERT INTO chat_messages (
            conversation_id,
            role,
            content,
            citations_json,
            tool_outputs_json,
            created_at
        ) VALUES (?, ?, ?, ?, ?, ?)
        """,
        (
            "conversation-1",
            role,
            "You have one overdue follow-up.",
            citations_json,
            tool_outputs_json,
            "2026-07-31T00:00:00Z",
        ),
    )


def insert_classification_run(
    connection: sqlite3.Connection,
    **overrides: object,
) -> None:
    values = {
        "id": "classification-run-1",
        "provider": "azure_openai",
        "model": "gpt-4.1-mini",
        "prompt_version": "prompt-v1",
        "started_at": "2026-07-05T12:00:00+00:00",
        "completed_at": "2026-07-05T12:02:00+00:00",
        "candidate_count": 3,
        "classified_count": 3,
        "prompt_tokens": 120,
        "completion_tokens": 30,
        "total_tokens": 150,
        "estimated_cost_usd": 0.00045,
    } | overrides
    connection.execute(
        """
        INSERT INTO classification_runs (
            id,
            provider,
            model,
            prompt_version,
            started_at,
            completed_at,
            candidate_count,
            classified_count,
            prompt_tokens,
            completion_tokens,
            total_tokens,
            estimated_cost_usd
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            values["id"],
            values["provider"],
            values["model"],
            values["prompt_version"],
            values["started_at"],
            values["completed_at"],
            values["candidate_count"],
            values["classified_count"],
            values["prompt_tokens"],
            values["completion_tokens"],
            values["total_tokens"],
            values["estimated_cost_usd"],
        ),
    )


def load_sqlite_vec(connection: sqlite3.Connection) -> None:
    sqlite_vec = import_module("sqlite_vec")
    load = getattr(sqlite_vec, "load", None)
    if not callable(load):
        raise RuntimeError("sqlite_vec.load is unavailable")

    connection.enable_load_extension(True)
    try:
        load(connection)
    finally:
        connection.enable_load_extension(False)
