from __future__ import annotations

import sqlite3
from pathlib import Path

from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from app.db.migrations.config import (
    include_autogenerated_object,
    migration_context_options,
)
from app.db.sqlite_url import sqlite_sync_database_url
from sqlalchemy import Column, Integer, MetaData, Table

BACKEND_ROOT = Path(__file__).resolve().parents[1]


def alembic_config(database_url: str | None = None) -> Config:
    config = Config(str(BACKEND_ROOT / "alembic.ini"))
    if database_url is not None:
        config.set_main_option("sqlalchemy.url", database_url)
    return config


def test_alembic_config_points_to_app_migrations_directory() -> None:
    config = alembic_config()
    script = ScriptDirectory.from_config(config)
    script_location = config.get_main_option("script_location")

    assert script_location is not None
    assert Path(script_location) == BACKEND_ROOT / "app" / "db" / "migrations"
    assert Path(script.dir) == BACKEND_ROOT / "app" / "db" / "migrations"
    assert Path(script.versions) == BACKEND_ROOT / "app" / "db" / "migrations" / "versions"


def test_alembic_context_options_enable_sqlite_batch_mode() -> None:
    options = migration_context_options()

    assert options["render_as_batch"] is True
    assert options["compare_type"] is True
    assert options["include_object"] is include_autogenerated_object


def test_sqlite_sync_database_url_preserves_sqlite_slash_forms(tmp_path: Path) -> None:
    database_path = tmp_path / "jobtracker.sqlite3"

    assert sqlite_sync_database_url("sqlite+aiosqlite:///./.jobtracker/jobtracker.sqlite3") == (
        "sqlite:///./.jobtracker/jobtracker.sqlite3"
    )
    assert sqlite_sync_database_url(f"sqlite+aiosqlite:///{database_path}") == (
        f"sqlite:///{database_path}"
    )
    assert sqlite_sync_database_url("sqlite:///./.jobtracker/jobtracker.sqlite3") == (
        "sqlite:///./.jobtracker/jobtracker.sqlite3"
    )


def test_virtual_tables_are_excluded_from_autogenerate() -> None:
    metadata = MetaData()
    regular_table = Table("raw_emails", metadata, Column("id", Integer, primary_key=True))
    virtual_table = Table(
        "email_chunks",
        metadata,
        Column("rowid", Integer, primary_key=True),
        info={"sqlite_virtual": True},
    )

    assert include_autogenerated_object(regular_table, "raw_emails", "table", False, None)
    assert not include_autogenerated_object(virtual_table, "email_chunks", "table", False, None)


def test_alembic_can_create_version_table_against_sqlite(tmp_path: Path) -> None:
    database_path = tmp_path / "jobtracker.sqlite3"
    config = alembic_config(f"sqlite+aiosqlite:///{database_path}")

    command.ensure_version(config)

    with sqlite3.connect(database_path) as connection:
        table_names = {
            row[0]
            for row in connection.execute(
                "SELECT name FROM sqlite_master WHERE type = 'table'",
            )
        }

    assert "alembic_version" in table_names
