/**
 * Generated by orval.
 * Do not edit manually.
 * Job Search Intelligence API
 * OpenAPI spec version: 0.1.0
 */
export type ApiErrorCode = (typeof ApiErrorCode)[keyof typeof ApiErrorCode];

export const ApiErrorCode = {
  bad_gateway: "bad_gateway",
  bad_request: "bad_request",
  conflict: "conflict",
  email_authorization_required: "email_authorization_required",
  email_insufficient_scope: "email_insufficient_scope",
  email_invalid_provider_response: "email_invalid_provider_response",
  email_provider_request_failed: "email_provider_request_failed",
  email_rate_limited: "email_rate_limited",
  email_sync_cursor_expired: "email_sync_cursor_expired",
  email_temporarily_unavailable: "email_temporarily_unavailable",
  forbidden: "forbidden",
  http_error: "http_error",
  internal_error: "internal_error",
  not_found: "not_found",
  service_unavailable: "service_unavailable",
  unauthorized: "unauthorized",
  validation_error: "validation_error",
} as const;

export interface ApiErrorDetail {
  field?: string | null;
  message: string;
  type: string;
}

export interface ApiErrorBody {
  code: ApiErrorCode;
  details?: ApiErrorDetail[];
  message: string;
}

export interface ApiErrorResponse {
  error: ApiErrorBody;
}

export type ClassificationMode =
  (typeof ClassificationMode)[keyof typeof ClassificationMode];

export const ClassificationMode = {
  hybrid: "hybrid",
  llm: "llm",
  local: "local",
} as const;

export type EmailProviderName =
  (typeof EmailProviderName)[keyof typeof EmailProviderName];

export const EmailProviderName = {
  gmail: "gmail",
} as const;

/**
 * Provider-neutral stable reference to a connected mailbox account.
 */
export interface EmailAccountRef {
  /** @minLength 1 */
  account_id: string;
  provider: EmailProviderName;
}

export interface EmailAddress {
  /** @minLength 1 */
  address: string;
  display_name?: string | null;
}

/**
 * Provider-neutral authorization URL and scope request.
 */
export interface EmailAuthorizationStartResult {
  /** @minLength 1 */
  authorization_url: string;
  provider: EmailProviderName;
  /** @minItems 1 */
  requested_scopes: string[];
  /** @minLength 1 */
  state: string;
}

export type SecretKind = (typeof SecretKind)[keyof typeof SecretKind];

export const SecretKind = {
  oauth_token: "oauth_token",
  llm_api_key: "llm_api_key",
} as const;

/**
 * Stable non-secret identifier for a stored secret.
 */
export interface SecretRef {
  kind: SecretKind;
  /**
   * @minLength 1
   * @maxLength 100
   * @pattern ^[a-z0-9][a-z0-9_.:-]*$
   */
  name: string;
  /**
   * @minLength 1
   * @maxLength 100
   * @pattern ^[a-z0-9][a-z0-9_.:-]*$
   */
  provider: string;
}

/**
 * Stored account connection metadata without raw OAuth token material.
 */
export interface EmailConnection {
  account: EmailAccountRef;
  connected_at: string;
  credential_expires_at?: string | null;
  credential_ref: SecretRef;
  display_email?: EmailAddress | null;
  /** @minItems 1 */
  granted_scopes: string[];
  reauth_required?: boolean;
}

export type ProviderRequirementEnforcement =
  (typeof ProviderRequirementEnforcement)[keyof typeof ProviderRequirementEnforcement];

export const ProviderRequirementEnforcement = {
  declarative: "declarative",
  selection: "selection",
} as const;

/**
 * Non-secret provider setting required by a supported provider.
 */
export interface ProviderConfigRequirementResponse {
  enforcement: ProviderRequirementEnforcement;
  label: string;
  required: boolean;
  setting_name: string;
}

/**
 * Secret reference metadata without the secret value.
 */
export interface ProviderSecretRequirementResponse {
  enforcement: ProviderRequirementEnforcement;
  label: string;
  ref: SecretRef;
  required: boolean;
}

/**
 * Email provider metadata exposed by the provider config API shell.
 */
export interface EmailProviderConfigResponse {
  config_requirements: ProviderConfigRequirementResponse[];
  display_name: string;
  name: EmailProviderName;
  secret_requirements: ProviderSecretRequirementResponse[];
}

export type EmailSyncMode = (typeof EmailSyncMode)[keyof typeof EmailSyncMode];

export const EmailSyncMode = {
  full_backfill: "full_backfill",
  incremental: "incremental",
} as const;

export type EmailSyncRunState =
  (typeof EmailSyncRunState)[keyof typeof EmailSyncRunState];

export const EmailSyncRunState = {
  idle: "idle",
  running: "running",
  succeeded: "succeeded",
  failed: "failed",
} as const;

/**
 * Current or last manual sync run status exposed at the API boundary.
 */
export interface EmailSyncStatus {
  account_id?: string | null;
  finished_at?: string | null;
  last_error?: string | null;
  /** @minimum 0 */
  message_count?: number;
  mode?: EmailSyncMode | null;
  /** @minimum 0 */
  page_count?: number;
  provider?: EmailProviderName | null;
  /** @minimum 0 */
  raw_email_count?: number;
  recovered_from_expired_cursor?: boolean;
  started_at?: string | null;
  state: EmailSyncRunState;
}

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  ctx?: ValidationErrorCtx;
  input?: unknown;
  loc: (string | number)[];
  msg: string;
  type: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export const HealthResponseValue = {
  status: "ok",
} as const;
export type HealthResponse = typeof HealthResponseValue;

export type LLMProviderName =
  (typeof LLMProviderName)[keyof typeof LLMProviderName];

export const LLMProviderName = {
  azure_openai: "azure_openai",
  ollama: "ollama",
} as const;

/**
 * LLM provider metadata exposed by the provider config API shell.
 */
export interface LLMProviderConfigResponse {
  config_requirements: ProviderConfigRequirementResponse[];
  display_name: string;
  is_local: boolean;
  name: LLMProviderName;
  secret_requirements: ProviderSecretRequirementResponse[];
}

/**
 * Currently selected provider choices for the setup/config shell.
 */
export interface ProviderSelection {
  classification_mode: ClassificationMode;
  email_provider: EmailProviderName;
  llm_provider: LLMProviderName;
}

/**
 * Non-secret provider settings visible at the API boundary.
 */
export interface ProviderConfigValues {
  azure_openai_api_version: string;
  azure_openai_chat_deployment: string;
  azure_openai_embedding_deployment: string;
  azure_openai_endpoint: string;
  gmail_client_config_file: string;
  gmail_scopes: string[];
  ollama_base_url: string;
  ollama_chat_model: string;
  ollama_embedding_model: string;
}

/**
 * Selected provider config plus supported provider metadata.
 */
export interface ProviderConfigResponse {
  email_providers: EmailProviderConfigResponse[];
  llm_providers: LLMProviderConfigResponse[];
  selection: ProviderSelection;
  settings: ProviderConfigValues;
}

/**
 * Partial in-process update for non-secret Phase 0 provider config.
 */
export interface ProviderConfigUpdateRequest {
  azure_openai_api_version?: string | null;
  azure_openai_chat_deployment?: string | null;
  azure_openai_embedding_deployment?: string | null;
  azure_openai_endpoint?: string | null;
  classification_mode?: ClassificationMode | null;
  email_provider?: EmailProviderName | null;
  gmail_client_config_file?: string | null;
  gmail_scopes?: string[] | null;
  llm_provider?: LLMProviderName | null;
  ollama_base_url?: string | null;
  ollama_chat_model?: string | null;
  ollama_embedding_model?: string | null;
}

/**
 * First-run setup readiness and selected non-secret provider settings.
 */
export interface SetupStatusResponse {
  classification_mode: ClassificationMode;
  email_provider: EmailProviderName;
  gmail_connected: boolean;
  llm_configured: boolean;
  llm_provider: LLMProviderName;
  setup_complete: boolean;
}

/**
 * Non-secret first-run setup choices accepted by the Phase 0 API shell.
 */
export interface SetupSubmitRequest {
  azure_openai_api_version?: string | null;
  azure_openai_chat_deployment?: string | null;
  azure_openai_embedding_deployment?: string | null;
  azure_openai_endpoint?: string | null;
  classification_mode: ClassificationMode;
  email_provider?: EmailProviderName;
  gmail_client_config_file?: string | null;
  llm_provider: LLMProviderName;
  ollama_base_url?: string | null;
  ollama_chat_model?: string | null;
  ollama_embedding_model?: string | null;
}

/**
 * Acknowledgement for a setup submission that has not persisted secrets yet.
 */
export interface SetupSubmitResponse {
  classification_mode: ClassificationMode;
  email_provider: EmailProviderName;
  gmail_connected: boolean;
  llm_configured: boolean;
  llm_provider: LLMProviderName;
  setup_complete: boolean;
  status: "accepted";
}

export const WipeDataRequestValue = {
  /** Must exactly equal wipe-local-data to confirm local data deletion. */
  confirmation: "wipe-local-data",
} as const;
export type WipeDataRequest = typeof WipeDataRequestValue;

export interface WipeDataResponse {
  /** Canonical local filesystem paths deleted by the wipe operation. */
  deleted_paths?: string[];
  /** Canonical local filesystem paths that were already absent. */
  missing_paths?: string[];
  status: "wiped";
}

export type GmailAuthCallbackAuthGmailCallbackGetParams = {
  /**
   * @minLength 1
   */
  code: string;
  /**
   * @minLength 1
   */
  state: string;
};

export type gmailAuthUrlAuthGmailGetResponse200 = {
  data: EmailAuthorizationStartResult;
  status: 200;
};

export type gmailAuthUrlAuthGmailGetResponse400 = {
  data: ApiErrorResponse;
  status: 400;
};

export type gmailAuthUrlAuthGmailGetResponseSuccess =
  gmailAuthUrlAuthGmailGetResponse200 & {
    headers: Headers;
  };
export type gmailAuthUrlAuthGmailGetResponseError =
  gmailAuthUrlAuthGmailGetResponse400 & {
    headers: Headers;
  };

export type gmailAuthUrlAuthGmailGetResponse =
  | gmailAuthUrlAuthGmailGetResponseSuccess
  | gmailAuthUrlAuthGmailGetResponseError;

export const getGmailAuthUrlAuthGmailGetUrl = () => {
  return `/auth/gmail`;
};

/**
 * @summary Gmail Auth Url
 */
export const gmailAuthUrlAuthGmailGet = async (
  options?: RequestInit,
): Promise<gmailAuthUrlAuthGmailGetResponse> => {
  const res = await fetch(getGmailAuthUrlAuthGmailGetUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: gmailAuthUrlAuthGmailGetResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as gmailAuthUrlAuthGmailGetResponse;
};

export type gmailAuthCallbackAuthGmailCallbackGetResponse200 = {
  data: EmailConnection;
  status: 200;
};

export type gmailAuthCallbackAuthGmailCallbackGetResponse400 = {
  data: ApiErrorResponse;
  status: 400;
};

export type gmailAuthCallbackAuthGmailCallbackGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type gmailAuthCallbackAuthGmailCallbackGetResponseSuccess =
  gmailAuthCallbackAuthGmailCallbackGetResponse200 & {
    headers: Headers;
  };
export type gmailAuthCallbackAuthGmailCallbackGetResponseError = (
  | gmailAuthCallbackAuthGmailCallbackGetResponse400
  | gmailAuthCallbackAuthGmailCallbackGetResponse422
) & {
  headers: Headers;
};

export type gmailAuthCallbackAuthGmailCallbackGetResponse =
  | gmailAuthCallbackAuthGmailCallbackGetResponseSuccess
  | gmailAuthCallbackAuthGmailCallbackGetResponseError;

export const getGmailAuthCallbackAuthGmailCallbackGetUrl = (
  params: GmailAuthCallbackAuthGmailCallbackGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/auth/gmail/callback?${stringifiedParams}`
    : `/auth/gmail/callback`;
};

/**
 * @summary Gmail Auth Callback
 */
export const gmailAuthCallbackAuthGmailCallbackGet = async (
  params: GmailAuthCallbackAuthGmailCallbackGetParams,
  options?: RequestInit,
): Promise<gmailAuthCallbackAuthGmailCallbackGetResponse> => {
  const res = await fetch(getGmailAuthCallbackAuthGmailCallbackGetUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: gmailAuthCallbackAuthGmailCallbackGetResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as gmailAuthCallbackAuthGmailCallbackGetResponse;
};

export type getProviderConfigConfigProvidersGetResponse200 = {
  data: ProviderConfigResponse;
  status: 200;
};

export type getProviderConfigConfigProvidersGetResponseSuccess =
  getProviderConfigConfigProvidersGetResponse200 & {
    headers: Headers;
  };
export type getProviderConfigConfigProvidersGetResponse =
  getProviderConfigConfigProvidersGetResponseSuccess;

export const getGetProviderConfigConfigProvidersGetUrl = () => {
  return `/config/providers`;
};

/**
 * Return selected provider config and non-secret supported-provider metadata.
 * @summary Get Provider Config
 */
export const getProviderConfigConfigProvidersGet = async (
  options?: RequestInit,
): Promise<getProviderConfigConfigProvidersGetResponse> => {
  const res = await fetch(getGetProviderConfigConfigProvidersGetUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getProviderConfigConfigProvidersGetResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getProviderConfigConfigProvidersGetResponse;
};

export type updateProviderConfigConfigProvidersPutResponse200 = {
  data: ProviderConfigResponse;
  status: 200;
};

export type updateProviderConfigConfigProvidersPutResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type updateProviderConfigConfigProvidersPutResponseSuccess =
  updateProviderConfigConfigProvidersPutResponse200 & {
    headers: Headers;
  };
export type updateProviderConfigConfigProvidersPutResponseError =
  updateProviderConfigConfigProvidersPutResponse422 & {
    headers: Headers;
  };

export type updateProviderConfigConfigProvidersPutResponse =
  | updateProviderConfigConfigProvidersPutResponseSuccess
  | updateProviderConfigConfigProvidersPutResponseError;

export const getUpdateProviderConfigConfigProvidersPutUrl = () => {
  return `/config/providers`;
};

/**
 * Validate and update the in-process provider config shell.
 * @summary Update Provider Config
 */
export const updateProviderConfigConfigProvidersPut = async (
  providerConfigUpdateRequest: ProviderConfigUpdateRequest,
  options?: RequestInit,
): Promise<updateProviderConfigConfigProvidersPutResponse> => {
  const res = await fetch(getUpdateProviderConfigConfigProvidersPutUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(providerConfigUpdateRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateProviderConfigConfigProvidersPutResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as updateProviderConfigConfigProvidersPutResponse;
};

export type healthHealthGetResponse200 = {
  data: HealthResponse;
  status: 200;
};

export type healthHealthGetResponseSuccess = healthHealthGetResponse200 & {
  headers: Headers;
};
export type healthHealthGetResponse = healthHealthGetResponseSuccess;

export const getHealthHealthGetUrl = () => {
  return `/health`;
};

/**
 * @summary Health
 */
export const healthHealthGet = async (
  options?: RequestInit,
): Promise<healthHealthGetResponse> => {
  const res = await fetch(getHealthHealthGetUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: healthHealthGetResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as healthHealthGetResponse;
};

export type wipeDataLocalDataWipePostResponse200 = {
  data: WipeDataResponse;
  status: 200;
};

export type wipeDataLocalDataWipePostResponse400 = {
  data: ApiErrorResponse;
  status: 400;
};

export type wipeDataLocalDataWipePostResponse422 = {
  data: ApiErrorResponse;
  status: 422;
};

export type wipeDataLocalDataWipePostResponseSuccess =
  wipeDataLocalDataWipePostResponse200 & {
    headers: Headers;
  };
export type wipeDataLocalDataWipePostResponseError = (
  wipeDataLocalDataWipePostResponse400 | wipeDataLocalDataWipePostResponse422
) & {
  headers: Headers;
};

export type wipeDataLocalDataWipePostResponse =
  | wipeDataLocalDataWipePostResponseSuccess
  | wipeDataLocalDataWipePostResponseError;

export const getWipeDataLocalDataWipePostUrl = () => {
  return `/local-data/wipe`;
};

/**
 * Deletes configured local JobTracker data and derived artifacts after the request body confirms the exact wipe-local-data phrase. The service preflights every filesystem target and returns a typed 400 error instead of deleting anything when a target is unsafe.
 * @summary Wipe local app data
 */
export const wipeDataLocalDataWipePost = async (
  wipeDataRequest: WipeDataRequest,
  options?: RequestInit,
): Promise<wipeDataLocalDataWipePostResponse> => {
  const res = await fetch(getWipeDataLocalDataWipePostUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(wipeDataRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: wipeDataLocalDataWipePostResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as wipeDataLocalDataWipePostResponse;
};

export type setupSubmitSetupPostResponse200 = {
  data: SetupSubmitResponse;
  status: 200;
};

export type setupSubmitSetupPostResponse400 = {
  data: ApiErrorResponse;
  status: 400;
};

export type setupSubmitSetupPostResponse422 = {
  data: ApiErrorResponse;
  status: 422;
};

export type setupSubmitSetupPostResponseSuccess =
  setupSubmitSetupPostResponse200 & {
    headers: Headers;
  };
export type setupSubmitSetupPostResponseError = (
  setupSubmitSetupPostResponse400 | setupSubmitSetupPostResponse422
) & {
  headers: Headers;
};

export type setupSubmitSetupPostResponse =
  setupSubmitSetupPostResponseSuccess | setupSubmitSetupPostResponseError;

export const getSetupSubmitSetupPostUrl = () => {
  return `/setup`;
};

/**
 * Accepts non-secret Phase 0 setup choices and validates selected provider metadata without running provider auth flows or persisting secrets.
 * @summary Submit first-run setup choices
 */
export const setupSubmitSetupPost = async (
  setupSubmitRequest: SetupSubmitRequest,
  options?: RequestInit,
): Promise<setupSubmitSetupPostResponse> => {
  const res = await fetch(getSetupSubmitSetupPostUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(setupSubmitRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: setupSubmitSetupPostResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as setupSubmitSetupPostResponse;
};

export type setupStatusSetupStatusGetResponse200 = {
  data: SetupStatusResponse;
  status: 200;
};

export type setupStatusSetupStatusGetResponseSuccess =
  setupStatusSetupStatusGetResponse200 & {
    headers: Headers;
  };
export type setupStatusSetupStatusGetResponse =
  setupStatusSetupStatusGetResponseSuccess;

export const getSetupStatusSetupStatusGetUrl = () => {
  return `/setup/status`;
};

/**
 * Report the Phase 0 setup shell without validating or exposing secrets.
 * @summary Setup Status
 */
export const setupStatusSetupStatusGet = async (
  options?: RequestInit,
): Promise<setupStatusSetupStatusGetResponse> => {
  const res = await fetch(getSetupStatusSetupStatusGetUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: setupStatusSetupStatusGetResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as setupStatusSetupStatusGetResponse;
};

export type syncNowSyncPostResponse200 = {
  data: EmailSyncStatus;
  status: 200;
};

export type syncNowSyncPostResponse400 = {
  data: ApiErrorResponse;
  status: 400;
};

export type syncNowSyncPostResponse409 = {
  data: ApiErrorResponse;
  status: 409;
};

export type syncNowSyncPostResponseSuccess = syncNowSyncPostResponse200 & {
  headers: Headers;
};
export type syncNowSyncPostResponseError = (
  syncNowSyncPostResponse400 | syncNowSyncPostResponse409
) & {
  headers: Headers;
};

export type syncNowSyncPostResponse =
  syncNowSyncPostResponseSuccess | syncNowSyncPostResponseError;

export const getSyncNowSyncPostUrl = () => {
  return `/sync`;
};

/**
 * @summary Sync Now
 */
export const syncNowSyncPost = async (
  options?: RequestInit,
): Promise<syncNowSyncPostResponse> => {
  const res = await fetch(getSyncNowSyncPostUrl(), {
    ...options,
    method: "POST",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: syncNowSyncPostResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as syncNowSyncPostResponse;
};

export type syncStatusSyncStatusGetResponse200 = {
  data: EmailSyncStatus;
  status: 200;
};

export type syncStatusSyncStatusGetResponseSuccess =
  syncStatusSyncStatusGetResponse200 & {
    headers: Headers;
  };
export type syncStatusSyncStatusGetResponse =
  syncStatusSyncStatusGetResponseSuccess;

export const getSyncStatusSyncStatusGetUrl = () => {
  return `/sync/status`;
};

/**
 * Report the current email sync job status without exposing provider payloads.
 * @summary Sync Status
 */
export const syncStatusSyncStatusGet = async (
  options?: RequestInit,
): Promise<syncStatusSyncStatusGetResponse> => {
  const res = await fetch(getSyncStatusSyncStatusGetUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: syncStatusSyncStatusGetResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as syncStatusSyncStatusGetResponse;
};
