/**
 * Generated by orval.
 * Do not edit manually.
 * Job Search Intelligence API
 * OpenAPI spec version: 0.1.0
 */
export type ApiErrorCode = (typeof ApiErrorCode)[keyof typeof ApiErrorCode];

export const ApiErrorCode = {
  bad_gateway: "bad_gateway",
  bad_request: "bad_request",
  conflict: "conflict",
  email_authorization_required: "email_authorization_required",
  email_insufficient_scope: "email_insufficient_scope",
  email_invalid_provider_response: "email_invalid_provider_response",
  email_provider_request_failed: "email_provider_request_failed",
  email_rate_limited: "email_rate_limited",
  email_sync_cursor_expired: "email_sync_cursor_expired",
  email_temporarily_unavailable: "email_temporarily_unavailable",
  forbidden: "forbidden",
  http_error: "http_error",
  internal_error: "internal_error",
  llm_provider_invalid_response: "llm_provider_invalid_response",
  llm_provider_request_failed: "llm_provider_request_failed",
  llm_provider_timeout: "llm_provider_timeout",
  llm_provider_unavailable: "llm_provider_unavailable",
  not_found: "not_found",
  service_unavailable: "service_unavailable",
  unauthorized: "unauthorized",
  validation_error: "validation_error",
} as const;

export interface ApiErrorDetail {
  field?: string | null;
  message: string;
  type: string;
}

export interface ApiErrorBody {
  code: ApiErrorCode;
  details?: ApiErrorDetail[];
  message: string;
}

export interface ApiErrorResponse {
  error: ApiErrorBody;
}

export type ClassificationMode =
  (typeof ClassificationMode)[keyof typeof ClassificationMode];

export const ClassificationMode = {
  hybrid: "hybrid",
  llm: "llm",
  local: "local",
} as const;

export type LLMProviderName =
  (typeof LLMProviderName)[keyof typeof LLMProviderName];

export const LLMProviderName = {
  azure_openai: "azure_openai",
  ollama: "ollama",
} as const;

/**
 * Public pre-run estimate for a bulk classification pass.
 */
export interface ClassificationPreRunEstimate {
  /**
   * Retained candidate emails needing classification for the current model and prompt.
   * @minimum 0
   */
  candidate_count: number;
  classification_mode: ClassificationMode;
  /** True when the endpoint can report a cost estimate, including zero-cost local mode. */
  cost_estimate_available: boolean;
  /** Currency for estimated_cost_usd. */
  currency?: string;
  /**
   * Estimated completion/output tokens from the configured per-candidate budget.
   * @minimum 0
   */
  estimated_completion_tokens: number;
  /** Estimated USD cost, or null when non-local provider pricing is not configured. */
  estimated_cost_usd?: number | null;
  /**
   * Estimated prompt/input tokens from retained body text plus configured overhead.
   * @minimum 0
   */
  estimated_prompt_tokens: number;
  /**
   * Sum of estimated prompt and completion tokens.
   * @minimum 0
   */
  estimated_total_tokens: number;
  llm_provider: LLMProviderName;
  /** Configured classification model identifier used to decide stale rows. */
  model: string;
  /**
   * Configured classification prompt version used to decide stale rows.
   * @minLength 1
   */
  prompt_version: string;
  /**
   * Human-readable heuristic used for token estimates.
   * @minLength 1
   */
  token_estimate_method: string;
}

export type EmailProviderName =
  (typeof EmailProviderName)[keyof typeof EmailProviderName];

export const EmailProviderName = {
  gmail: "gmail",
} as const;

/**
 * Public read-only plan for controlled classification reprocessing.
 */
export interface ClassificationReprocessingPlan {
  /** @minimum 0 */
  blocked_by_missing_target_model_count: number;
  classification_mode: ClassificationMode;
  email_provider: EmailProviderName;
  llm_provider: LLMProviderName;
  /** @minimum 0 */
  reprocess_count: number;
  /** @minimum 0 */
  retained_candidate_count: number;
  /** @minLength 1 */
  selection_policy: string;
  should_reprocess: boolean;
  /** @minimum 0 */
  stale_model_count: number;
  /** @minimum 0 */
  stale_prompt_version_count: number;
  target_model: string;
  target_model_configured: boolean;
  /** @minLength 1 */
  target_prompt_version: string;
  /** @minimum 0 */
  unclassified_count: number;
  /** @minimum 0 */
  up_to_date_count: number;
}

/**
 * Public response for a completed classification batch run.
 */
export interface ClassificationRunResponse {
  /** @minimum 0 */
  candidate_count: number;
  classification_mode: ClassificationMode;
  /** @minimum 0 */
  classified_count: number;
  completed_at: string;
  /** @minimum 0 */
  completion_tokens: number;
  /** @minimum 0 */
  estimated_cost_usd: number;
  llm_provider: LLMProviderName;
  /** @minimum 0 */
  malformed_count: number;
  /** @minLength 1 */
  model: string;
  /** @minimum 0 */
  prompt_tokens: number;
  /** @minLength 1 */
  prompt_version: string;
  /** @minLength 1 */
  provider: string;
  /** @minLength 1 */
  run_id: string;
  started_at: string;
  /** @minimum 0 */
  total_tokens: number;
}

/**
 * Provider-neutral stable reference to a connected mailbox account.
 */
export interface EmailAccountRef {
  /** @minLength 1 */
  account_id: string;
  provider: EmailProviderName;
}

/**
 * Provider-normalized email address plus optional display name.
 *
 * Provider adapters should lower-case parsed addresses, trim display names,
 * and deduplicate repeated recipients before returning metadata DTOs.
 */
export interface EmailAddress {
  /** @minLength 1 */
  address: string;
  display_name?: string | null;
}

/**
 * Provider-neutral authorization URL and scope request.
 */
export interface EmailAuthorizationStartResult {
  /** @minLength 1 */
  authorization_url: string;
  provider: EmailProviderName;
  /** @minItems 1 */
  requested_scopes: string[];
  /** @minLength 1 */
  state: string;
}

export type SecretKind = (typeof SecretKind)[keyof typeof SecretKind];

export const SecretKind = {
  oauth_token: "oauth_token",
  llm_api_key: "llm_api_key",
} as const;

/**
 * Stable non-secret identifier for a stored secret.
 */
export interface SecretRef {
  kind: SecretKind;
  /**
   * @minLength 1
   * @maxLength 100
   * @pattern ^[a-z0-9][a-z0-9_.:-]*$
   */
  name: string;
  /**
   * @minLength 1
   * @maxLength 100
   * @pattern ^[a-z0-9][a-z0-9_.:-]*$
   */
  provider: string;
}

/**
 * Stored account connection metadata without raw OAuth token material.
 */
export interface EmailConnection {
  account: EmailAccountRef;
  connected_at: string;
  credential_expires_at?: string | null;
  credential_ref: SecretRef;
  display_email?: EmailAddress | null;
  /** @minItems 1 */
  granted_scopes: string[];
  reauth_required?: boolean;
}

export type ProviderRequirementEnforcement =
  (typeof ProviderRequirementEnforcement)[keyof typeof ProviderRequirementEnforcement];

export const ProviderRequirementEnforcement = {
  declarative: "declarative",
  selection: "selection",
} as const;

/**
 * Non-secret provider setting required by a supported provider.
 */
export interface ProviderConfigRequirementResponse {
  enforcement: ProviderRequirementEnforcement;
  label: string;
  required: boolean;
  setting_name: string;
}

/**
 * Secret reference metadata without the secret value.
 */
export interface ProviderSecretRequirementResponse {
  enforcement: ProviderRequirementEnforcement;
  label: string;
  ref: SecretRef;
  required: boolean;
}

/**
 * Email provider metadata exposed by the provider config API shell.
 */
export interface EmailProviderConfigResponse {
  config_requirements: ProviderConfigRequirementResponse[];
  display_name: string;
  name: EmailProviderName;
  secret_requirements: ProviderSecretRequirementResponse[];
}

export type EmailSyncMode = (typeof EmailSyncMode)[keyof typeof EmailSyncMode];

export const EmailSyncMode = {
  full_backfill: "full_backfill",
  incremental: "incremental",
} as const;

export type EmailSyncRunState =
  (typeof EmailSyncRunState)[keyof typeof EmailSyncRunState];

export const EmailSyncRunState = {
  idle: "idle",
  running: "running",
  succeeded: "succeeded",
  failed: "failed",
} as const;

/**
 * Current or last manual sync run status exposed at the API boundary.
 */
export interface EmailSyncStatus {
  account_id?: string | null;
  finished_at?: string | null;
  last_error?: string | null;
  /** @minimum 0 */
  message_count?: number;
  mode?: EmailSyncMode | null;
  /** @minimum 0 */
  page_count?: number;
  provider?: EmailProviderName | null;
  /** @minimum 0 */
  raw_email_count?: number;
  recovered_from_expired_cursor?: boolean;
  started_at?: string | null;
  state: EmailSyncRunState;
}

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  ctx?: ValidationErrorCtx;
  input?: unknown;
  loc: (string | number)[];
  msg: string;
  type: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export const HealthResponseValue = {
  status: "ok",
} as const;
export type HealthResponse = typeof HealthResponseValue;

export type LLMModelKind = (typeof LLMModelKind)[keyof typeof LLMModelKind];

export const LLMModelKind = {
  chat: "chat",
  embedding: "embedding",
} as const;

export type LLMModelHealthStatus =
  (typeof LLMModelHealthStatus)[keyof typeof LLMModelHealthStatus];

export const LLMModelHealthStatus = {
  available: "available",
  unavailable: "unavailable",
} as const;

/**
 * Availability result for one configured provider model.
 */
export interface LLMModelHealthCheck {
  detail?: string | null;
  kind: LLMModelKind;
  /** @minLength 1 */
  model: string;
  status: LLMModelHealthStatus;
}

/**
 * LLM provider metadata exposed by the provider config API shell.
 */
export interface LLMProviderConfigResponse {
  config_requirements: ProviderConfigRequirementResponse[];
  display_name: string;
  is_local: boolean;
  name: LLMProviderName;
  secret_requirements: ProviderSecretRequirementResponse[];
}

/**
 * Provider-neutral health-check result for the selected LLM provider.
 */
export interface LLMProviderHealthCheckResponse {
  /** @minItems 1 */
  checks: LLMModelHealthCheck[];
  /** @minLength 1 */
  provider_name: string;
  status: LLMModelHealthStatus;
}

/**
 * Currently selected provider choices for the setup/config shell.
 */
export interface ProviderSelection {
  classification_mode: ClassificationMode;
  email_provider: EmailProviderName;
  llm_provider: LLMProviderName;
}

/**
 * Non-secret provider settings visible at the API boundary.
 */
export interface ProviderConfigValues {
  azure_openai_api_version: string;
  azure_openai_chat_deployment: string;
  azure_openai_embedding_deployment: string;
  azure_openai_endpoint: string;
  gmail_client_config_file: string;
  gmail_scopes: string[];
  ollama_base_url: string;
  ollama_chat_model: string;
  ollama_embedding_model: string;
}

/**
 * Selected provider config plus supported provider metadata.
 */
export interface ProviderConfigResponse {
  email_providers: EmailProviderConfigResponse[];
  llm_providers: LLMProviderConfigResponse[];
  recommended_classification_mode: ClassificationMode;
  selection: ProviderSelection;
  settings: ProviderConfigValues;
}

/**
 * Partial in-process update for non-secret Phase 0 provider config.
 */
export interface ProviderConfigUpdateRequest {
  azure_openai_api_version?: string | null;
  azure_openai_chat_deployment?: string | null;
  azure_openai_embedding_deployment?: string | null;
  azure_openai_endpoint?: string | null;
  classification_mode?: ClassificationMode | null;
  email_provider?: EmailProviderName | null;
  gmail_client_config_file?: string | null;
  gmail_scopes?: string[] | null;
  llm_provider?: LLMProviderName | null;
  ollama_base_url?: string | null;
  ollama_chat_model?: string | null;
  ollama_embedding_model?: string | null;
}

/**
 * First-run setup readiness and selected non-secret provider settings.
 */
export interface SetupStatusResponse {
  classification_mode: ClassificationMode;
  email_provider: EmailProviderName;
  gmail_connected: boolean;
  llm_configured: boolean;
  llm_provider: LLMProviderName;
  recommended_classification_mode: ClassificationMode;
  setup_complete: boolean;
}

/**
 * Non-secret first-run setup choices accepted by the Phase 0 API shell.
 */
export interface SetupSubmitRequest {
  azure_openai_api_version?: string | null;
  azure_openai_chat_deployment?: string | null;
  azure_openai_embedding_deployment?: string | null;
  azure_openai_endpoint?: string | null;
  classification_mode?: ClassificationMode | null;
  email_provider?: EmailProviderName;
  gmail_client_config_file?: string | null;
  llm_provider: LLMProviderName;
  ollama_base_url?: string | null;
  ollama_chat_model?: string | null;
  ollama_embedding_model?: string | null;
}

/**
 * Acknowledgement for a setup submission that has not persisted secrets yet.
 */
export interface SetupSubmitResponse {
  classification_mode: ClassificationMode;
  email_provider: EmailProviderName;
  gmail_connected: boolean;
  llm_configured: boolean;
  llm_provider: LLMProviderName;
  recommended_classification_mode: ClassificationMode;
  setup_complete: boolean;
  status: "accepted";
}

export const WipeDataRequestValue = {
  /** Must exactly equal wipe-local-data to confirm local data deletion. */
  confirmation: "wipe-local-data",
} as const;
export type WipeDataRequest = typeof WipeDataRequestValue;

export interface WipeDataResponse {
  /** Canonical local filesystem paths deleted by the wipe operation. */
  deleted_paths?: string[];
  /** Canonical local filesystem paths that were already absent. */
  missing_paths?: string[];
  status: "wiped";
}

export type GmailAuthCallbackAuthGmailCallbackGetParams = {
  /**
   * @minLength 1
   */
  code: string;
  /**
   * @minLength 1
   */
  state: string;
};

export type gmailAuthUrlAuthGmailGetResponse200 = {
  data: EmailAuthorizationStartResult;
  status: 200;
};

export type gmailAuthUrlAuthGmailGetResponse400 = {
  data: ApiErrorResponse;
  status: 400;
};

export type gmailAuthUrlAuthGmailGetResponseSuccess =
  gmailAuthUrlAuthGmailGetResponse200 & {
    headers: Headers;
  };
export type gmailAuthUrlAuthGmailGetResponseError =
  gmailAuthUrlAuthGmailGetResponse400 & {
    headers: Headers;
  };

export type gmailAuthUrlAuthGmailGetResponse =
  | gmailAuthUrlAuthGmailGetResponseSuccess
  | gmailAuthUrlAuthGmailGetResponseError;

export const getGmailAuthUrlAuthGmailGetUrl = () => {
  return `/auth/gmail`;
};

/**
 * @summary Gmail Auth Url
 */
export const gmailAuthUrlAuthGmailGet = async (
  options?: RequestInit,
): Promise<gmailAuthUrlAuthGmailGetResponse> => {
  const res = await fetch(getGmailAuthUrlAuthGmailGetUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: gmailAuthUrlAuthGmailGetResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as gmailAuthUrlAuthGmailGetResponse;
};

export type gmailAuthCallbackAuthGmailCallbackGetResponse200 = {
  data: EmailConnection;
  status: 200;
};

export type gmailAuthCallbackAuthGmailCallbackGetResponse400 = {
  data: ApiErrorResponse;
  status: 400;
};

export type gmailAuthCallbackAuthGmailCallbackGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type gmailAuthCallbackAuthGmailCallbackGetResponseSuccess =
  gmailAuthCallbackAuthGmailCallbackGetResponse200 & {
    headers: Headers;
  };
export type gmailAuthCallbackAuthGmailCallbackGetResponseError = (
  | gmailAuthCallbackAuthGmailCallbackGetResponse400
  | gmailAuthCallbackAuthGmailCallbackGetResponse422
) & {
  headers: Headers;
};

export type gmailAuthCallbackAuthGmailCallbackGetResponse =
  | gmailAuthCallbackAuthGmailCallbackGetResponseSuccess
  | gmailAuthCallbackAuthGmailCallbackGetResponseError;

export const getGmailAuthCallbackAuthGmailCallbackGetUrl = (
  params: GmailAuthCallbackAuthGmailCallbackGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/auth/gmail/callback?${stringifiedParams}`
    : `/auth/gmail/callback`;
};

/**
 * @summary Gmail Auth Callback
 */
export const gmailAuthCallbackAuthGmailCallbackGet = async (
  params: GmailAuthCallbackAuthGmailCallbackGetParams,
  options?: RequestInit,
): Promise<gmailAuthCallbackAuthGmailCallbackGetResponse> => {
  const res = await fetch(getGmailAuthCallbackAuthGmailCallbackGetUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: gmailAuthCallbackAuthGmailCallbackGetResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as gmailAuthCallbackAuthGmailCallbackGetResponse;
};

export type classificationEstimateClassificationEstimateGetResponse200 = {
  data: ClassificationPreRunEstimate;
  status: 200;
};

export type classificationEstimateClassificationEstimateGetResponseSuccess =
  classificationEstimateClassificationEstimateGetResponse200 & {
    headers: Headers;
  };
export type classificationEstimateClassificationEstimateGetResponse =
  classificationEstimateClassificationEstimateGetResponseSuccess;

export const getClassificationEstimateClassificationEstimateGetUrl = () => {
  return `/classification/estimate`;
};

/**
 * Returns deterministic candidate counts, token estimates, and cost availability for a future bulk classification pass without calling an LLM or exposing email content.
 * @summary Estimate Classification Run
 */
export const classificationEstimateClassificationEstimateGet = async (
  options?: RequestInit,
): Promise<classificationEstimateClassificationEstimateGetResponse> => {
  const res = await fetch(
    getClassificationEstimateClassificationEstimateGetUrl(),
    {
      ...options,
      method: "GET",
    },
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: classificationEstimateClassificationEstimateGetResponse["data"] =
    body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as classificationEstimateClassificationEstimateGetResponse;
};

export type classificationReprocessingPlanClassificationReprocessingPlanGetResponse200 =
  {
    data: ClassificationReprocessingPlan;
    status: 200;
  };

export type classificationReprocessingPlanClassificationReprocessingPlanGetResponseSuccess =
  classificationReprocessingPlanClassificationReprocessingPlanGetResponse200 & {
    headers: Headers;
  };
export type classificationReprocessingPlanClassificationReprocessingPlanGetResponse =
  classificationReprocessingPlanClassificationReprocessingPlanGetResponseSuccess;

export const getClassificationReprocessingPlanClassificationReprocessingPlanGetUrl =
  () => {
    return `/classification/reprocessing-plan`;
  };

/**
 * Returns deterministic prompt/model-version buckets for retained classification candidates without calling an LLM or exposing email content.
 * @summary Plan Classification Reprocessing
 */
export const classificationReprocessingPlanClassificationReprocessingPlanGet =
  async (
    options?: RequestInit,
  ): Promise<classificationReprocessingPlanClassificationReprocessingPlanGetResponse> => {
    const res = await fetch(
      getClassificationReprocessingPlanClassificationReprocessingPlanGetUrl(),
      {
        ...options,
        method: "GET",
      },
    );

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: classificationReprocessingPlanClassificationReprocessingPlanGetResponse["data"] =
      body ? JSON.parse(body) : {};
    return {
      data,
      status: res.status,
      headers: res.headers,
    } as classificationReprocessingPlanClassificationReprocessingPlanGetResponse;
  };

export type classificationRunClassificationRunPostResponse200 = {
  data: ClassificationRunResponse;
  status: 200;
};

export type classificationRunClassificationRunPostResponseSuccess =
  classificationRunClassificationRunPostResponse200 & {
    headers: Headers;
  };
export type classificationRunClassificationRunPostResponse =
  classificationRunClassificationRunPostResponseSuccess;

export const getClassificationRunClassificationRunPostUrl = () => {
  return `/classification/run`;
};

/**
 * Classifies retained email candidates through the configured LLM provider and idempotently stores classification results plus run accounting.
 * @summary Run Classification Batch
 */
export const classificationRunClassificationRunPost = async (
  options?: RequestInit,
): Promise<classificationRunClassificationRunPostResponse> => {
  const res = await fetch(getClassificationRunClassificationRunPostUrl(), {
    ...options,
    method: "POST",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: classificationRunClassificationRunPostResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as classificationRunClassificationRunPostResponse;
};

export type getProviderConfigConfigProvidersGetResponse200 = {
  data: ProviderConfigResponse;
  status: 200;
};

export type getProviderConfigConfigProvidersGetResponseSuccess =
  getProviderConfigConfigProvidersGetResponse200 & {
    headers: Headers;
  };
export type getProviderConfigConfigProvidersGetResponse =
  getProviderConfigConfigProvidersGetResponseSuccess;

export const getGetProviderConfigConfigProvidersGetUrl = () => {
  return `/config/providers`;
};

/**
 * Return selected provider config plus recommended classification mode.
 * @summary Get Provider Config
 */
export const getProviderConfigConfigProvidersGet = async (
  options?: RequestInit,
): Promise<getProviderConfigConfigProvidersGetResponse> => {
  const res = await fetch(getGetProviderConfigConfigProvidersGetUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getProviderConfigConfigProvidersGetResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getProviderConfigConfigProvidersGetResponse;
};

export type updateProviderConfigConfigProvidersPutResponse200 = {
  data: ProviderConfigResponse;
  status: 200;
};

export type updateProviderConfigConfigProvidersPutResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type updateProviderConfigConfigProvidersPutResponseSuccess =
  updateProviderConfigConfigProvidersPutResponse200 & {
    headers: Headers;
  };
export type updateProviderConfigConfigProvidersPutResponseError =
  updateProviderConfigConfigProvidersPutResponse422 & {
    headers: Headers;
  };

export type updateProviderConfigConfigProvidersPutResponse =
  | updateProviderConfigConfigProvidersPutResponseSuccess
  | updateProviderConfigConfigProvidersPutResponseError;

export const getUpdateProviderConfigConfigProvidersPutUrl = () => {
  return `/config/providers`;
};

/**
 * Validate and update provider config, applying recommendations on provider changes.
 * @summary Update Provider Config
 */
export const updateProviderConfigConfigProvidersPut = async (
  providerConfigUpdateRequest: ProviderConfigUpdateRequest,
  options?: RequestInit,
): Promise<updateProviderConfigConfigProvidersPutResponse> => {
  const res = await fetch(getUpdateProviderConfigConfigProvidersPutUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(providerConfigUpdateRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateProviderConfigConfigProvidersPutResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as updateProviderConfigConfigProvidersPutResponse;
};

export type checkLlmProviderHealthConfigProvidersLlmHealthPostResponse200 = {
  data: LLMProviderHealthCheckResponse;
  status: 200;
};

export type checkLlmProviderHealthConfigProvidersLlmHealthPostResponseSuccess =
  checkLlmProviderHealthConfigProvidersLlmHealthPostResponse200 & {
    headers: Headers;
  };
export type checkLlmProviderHealthConfigProvidersLlmHealthPostResponse =
  checkLlmProviderHealthConfigProvidersLlmHealthPostResponseSuccess;

export const getCheckLlmProviderHealthConfigProvidersLlmHealthPostUrl = () => {
  return `/config/providers/llm/health`;
};

/**
 * Verify selected LLM provider models through the configured provider adapter.
 * @summary Check Llm Provider Health
 */
export const checkLlmProviderHealthConfigProvidersLlmHealthPost = async (
  options?: RequestInit,
): Promise<checkLlmProviderHealthConfigProvidersLlmHealthPostResponse> => {
  const res = await fetch(
    getCheckLlmProviderHealthConfigProvidersLlmHealthPostUrl(),
    {
      ...options,
      method: "POST",
    },
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: checkLlmProviderHealthConfigProvidersLlmHealthPostResponse["data"] =
    body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as checkLlmProviderHealthConfigProvidersLlmHealthPostResponse;
};

export type healthHealthGetResponse200 = {
  data: HealthResponse;
  status: 200;
};

export type healthHealthGetResponseSuccess = healthHealthGetResponse200 & {
  headers: Headers;
};
export type healthHealthGetResponse = healthHealthGetResponseSuccess;

export const getHealthHealthGetUrl = () => {
  return `/health`;
};

/**
 * @summary Health
 */
export const healthHealthGet = async (
  options?: RequestInit,
): Promise<healthHealthGetResponse> => {
  const res = await fetch(getHealthHealthGetUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: healthHealthGetResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as healthHealthGetResponse;
};

export type wipeDataLocalDataWipePostResponse200 = {
  data: WipeDataResponse;
  status: 200;
};

export type wipeDataLocalDataWipePostResponse400 = {
  data: ApiErrorResponse;
  status: 400;
};

export type wipeDataLocalDataWipePostResponse422 = {
  data: ApiErrorResponse;
  status: 422;
};

export type wipeDataLocalDataWipePostResponseSuccess =
  wipeDataLocalDataWipePostResponse200 & {
    headers: Headers;
  };
export type wipeDataLocalDataWipePostResponseError = (
  wipeDataLocalDataWipePostResponse400 | wipeDataLocalDataWipePostResponse422
) & {
  headers: Headers;
};

export type wipeDataLocalDataWipePostResponse =
  | wipeDataLocalDataWipePostResponseSuccess
  | wipeDataLocalDataWipePostResponseError;

export const getWipeDataLocalDataWipePostUrl = () => {
  return `/local-data/wipe`;
};

/**
 * Deletes configured local JobTracker data and derived artifacts after the request body confirms the exact wipe-local-data phrase. The service preflights every filesystem target and returns a typed 400 error instead of deleting anything when a target is unsafe.
 * @summary Wipe local app data
 */
export const wipeDataLocalDataWipePost = async (
  wipeDataRequest: WipeDataRequest,
  options?: RequestInit,
): Promise<wipeDataLocalDataWipePostResponse> => {
  const res = await fetch(getWipeDataLocalDataWipePostUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(wipeDataRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: wipeDataLocalDataWipePostResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as wipeDataLocalDataWipePostResponse;
};

export type setupSubmitSetupPostResponse200 = {
  data: SetupSubmitResponse;
  status: 200;
};

export type setupSubmitSetupPostResponse400 = {
  data: ApiErrorResponse;
  status: 400;
};

export type setupSubmitSetupPostResponse422 = {
  data: ApiErrorResponse;
  status: 422;
};

export type setupSubmitSetupPostResponseSuccess =
  setupSubmitSetupPostResponse200 & {
    headers: Headers;
  };
export type setupSubmitSetupPostResponseError = (
  setupSubmitSetupPostResponse400 | setupSubmitSetupPostResponse422
) & {
  headers: Headers;
};

export type setupSubmitSetupPostResponse =
  setupSubmitSetupPostResponseSuccess | setupSubmitSetupPostResponseError;

export const getSetupSubmitSetupPostUrl = () => {
  return `/setup`;
};

/**
 * Accepts non-secret Phase 0 setup choices and validates selected provider metadata without running provider auth flows or persisting secrets. When classification_mode is omitted, the backend applies the selected provider recommendation before validation.
 * @summary Submit first-run setup choices
 */
export const setupSubmitSetupPost = async (
  setupSubmitRequest: SetupSubmitRequest,
  options?: RequestInit,
): Promise<setupSubmitSetupPostResponse> => {
  const res = await fetch(getSetupSubmitSetupPostUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(setupSubmitRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: setupSubmitSetupPostResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as setupSubmitSetupPostResponse;
};

export type setupStatusSetupStatusGetResponse200 = {
  data: SetupStatusResponse;
  status: 200;
};

export type setupStatusSetupStatusGetResponseSuccess =
  setupStatusSetupStatusGetResponse200 & {
    headers: Headers;
  };
export type setupStatusSetupStatusGetResponse =
  setupStatusSetupStatusGetResponseSuccess;

export const getSetupStatusSetupStatusGetUrl = () => {
  return `/setup/status`;
};

/**
 * Report setup status plus current and recommended classification modes.
 * @summary Setup Status
 */
export const setupStatusSetupStatusGet = async (
  options?: RequestInit,
): Promise<setupStatusSetupStatusGetResponse> => {
  const res = await fetch(getSetupStatusSetupStatusGetUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: setupStatusSetupStatusGetResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as setupStatusSetupStatusGetResponse;
};

export type syncNowSyncPostResponse200 = {
  data: EmailSyncStatus;
  status: 200;
};

export type syncNowSyncPostResponse400 = {
  data: ApiErrorResponse;
  status: 400;
};

export type syncNowSyncPostResponse401 = {
  data: ApiErrorResponse;
  status: 401;
};

export type syncNowSyncPostResponse403 = {
  data: ApiErrorResponse;
  status: 403;
};

export type syncNowSyncPostResponse409 = {
  data: ApiErrorResponse;
  status: 409;
};

export type syncNowSyncPostResponse429 = {
  data: ApiErrorResponse;
  status: 429;
};

export type syncNowSyncPostResponse502 = {
  data: ApiErrorResponse;
  status: 502;
};

export type syncNowSyncPostResponse503 = {
  data: ApiErrorResponse;
  status: 503;
};

export type syncNowSyncPostResponseSuccess = syncNowSyncPostResponse200 & {
  headers: Headers;
};
export type syncNowSyncPostResponseError = (
  | syncNowSyncPostResponse400
  | syncNowSyncPostResponse401
  | syncNowSyncPostResponse403
  | syncNowSyncPostResponse409
  | syncNowSyncPostResponse429
  | syncNowSyncPostResponse502
  | syncNowSyncPostResponse503
) & {
  headers: Headers;
};

export type syncNowSyncPostResponse =
  syncNowSyncPostResponseSuccess | syncNowSyncPostResponseError;

export const getSyncNowSyncPostUrl = () => {
  return `/sync`;
};

/**
 * @summary Sync Now
 */
export const syncNowSyncPost = async (
  options?: RequestInit,
): Promise<syncNowSyncPostResponse> => {
  const res = await fetch(getSyncNowSyncPostUrl(), {
    ...options,
    method: "POST",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: syncNowSyncPostResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as syncNowSyncPostResponse;
};

export type syncStatusSyncStatusGetResponse200 = {
  data: EmailSyncStatus;
  status: 200;
};

export type syncStatusSyncStatusGetResponseSuccess =
  syncStatusSyncStatusGetResponse200 & {
    headers: Headers;
  };
export type syncStatusSyncStatusGetResponse =
  syncStatusSyncStatusGetResponseSuccess;

export const getSyncStatusSyncStatusGetUrl = () => {
  return `/sync/status`;
};

/**
 * Report the current email sync job status without exposing provider payloads.
 * @summary Sync Status
 */
export const syncStatusSyncStatusGet = async (
  options?: RequestInit,
): Promise<syncStatusSyncStatusGetResponse> => {
  const res = await fetch(getSyncStatusSyncStatusGetUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: syncStatusSyncStatusGetResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as syncStatusSyncStatusGetResponse;
};
