/**
 * Generated by orval.
 * Do not edit manually.
 * Job Search Intelligence API
 * OpenAPI spec version: 0.1.0
 */
export type ClassificationMode =
  (typeof ClassificationMode)[keyof typeof ClassificationMode];

export const ClassificationMode = {
  hybrid: "hybrid",
  llm: "llm",
  local: "local",
} as const;

export type EmailProviderName =
  (typeof EmailProviderName)[keyof typeof EmailProviderName];

export const EmailProviderName = {
  gmail: "gmail",
} as const;

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  ctx?: ValidationErrorCtx;
  input?: unknown;
  loc: (string | number)[];
  msg: string;
  type: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export const HealthResponseValue = {
  status: "ok",
} as const;
export type HealthResponse = typeof HealthResponseValue;

export type LLMProviderName =
  (typeof LLMProviderName)[keyof typeof LLMProviderName];

export const LLMProviderName = {
  azure_openai: "azure_openai",
  ollama: "ollama",
} as const;

/**
 * First-run setup readiness and selected non-secret provider settings.
 */
export interface SetupStatusResponse {
  classification_mode: ClassificationMode;
  email_provider: EmailProviderName;
  gmail_connected: boolean;
  llm_configured: boolean;
  llm_provider: LLMProviderName;
  setup_complete: boolean;
}

export const WipeDataRequestValue = {
  /** Must exactly equal wipe-local-data to confirm local data deletion. */
  confirmation: "wipe-local-data",
} as const;
export type WipeDataRequest = typeof WipeDataRequestValue;

export interface WipeDataResponse {
  /** Canonical local filesystem paths deleted by the wipe operation. */
  deleted_paths?: string[];
  /** Canonical local filesystem paths that were already absent. */
  missing_paths?: string[];
  status: "wiped";
}

export type healthHealthGetResponse200 = {
  data: HealthResponse;
  status: 200;
};

export type healthHealthGetResponseSuccess = healthHealthGetResponse200 & {
  headers: Headers;
};
export type healthHealthGetResponse = healthHealthGetResponseSuccess;

export const getHealthHealthGetUrl = () => {
  return `/health`;
};

/**
 * @summary Health
 */
export const healthHealthGet = async (
  options?: RequestInit,
): Promise<healthHealthGetResponse> => {
  const res = await fetch(getHealthHealthGetUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: healthHealthGetResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as healthHealthGetResponse;
};

export type wipeDataLocalDataWipePostResponse200 = {
  data: WipeDataResponse;
  status: 200;
};

export type wipeDataLocalDataWipePostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type wipeDataLocalDataWipePostResponseSuccess =
  wipeDataLocalDataWipePostResponse200 & {
    headers: Headers;
  };
export type wipeDataLocalDataWipePostResponseError =
  wipeDataLocalDataWipePostResponse422 & {
    headers: Headers;
  };

export type wipeDataLocalDataWipePostResponse =
  | wipeDataLocalDataWipePostResponseSuccess
  | wipeDataLocalDataWipePostResponseError;

export const getWipeDataLocalDataWipePostUrl = () => {
  return `/local-data/wipe`;
};

/**
 * Deletes configured local JobTracker data and derived artifacts after the request body confirms the exact wipe-local-data phrase. The service preflights every filesystem target and returns a typed 400 error instead of deleting anything when a target is unsafe.
 * @summary Wipe local app data
 */
export const wipeDataLocalDataWipePost = async (
  wipeDataRequest: WipeDataRequest,
  options?: RequestInit,
): Promise<wipeDataLocalDataWipePostResponse> => {
  const res = await fetch(getWipeDataLocalDataWipePostUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(wipeDataRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: wipeDataLocalDataWipePostResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as wipeDataLocalDataWipePostResponse;
};

export type setupStatusSetupStatusGetResponse200 = {
  data: SetupStatusResponse;
  status: 200;
};

export type setupStatusSetupStatusGetResponseSuccess =
  setupStatusSetupStatusGetResponse200 & {
    headers: Headers;
  };
export type setupStatusSetupStatusGetResponse =
  setupStatusSetupStatusGetResponseSuccess;

export const getSetupStatusSetupStatusGetUrl = () => {
  return `/setup/status`;
};

/**
 * Report the Phase 0 setup shell without validating or exposing secrets.
 * @summary Setup Status
 */
export const setupStatusSetupStatusGet = async (
  options?: RequestInit,
): Promise<setupStatusSetupStatusGetResponse> => {
  const res = await fetch(getSetupStatusSetupStatusGetUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: setupStatusSetupStatusGetResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as setupStatusSetupStatusGetResponse;
};
